//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace DataAccess
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>AccountBusinessResult</summary>
		AccountBusinessResultEntity,
		///<summary>AccountCashFlowItem</summary>
		AccountCashFlowItemEntity,
		///<summary>AccountCostCalculatingItem</summary>
		AccountCostCalculatingItemEntity,
		///<summary>AccountTaxObligation</summary>
		AccountTaxObligationEntity,
		///<summary>AccountVat3Item</summary>
		AccountVat3ItemEntity,
		///<summary>AccountVatDeclareItem</summary>
		AccountVatDeclareItemEntity,
		///<summary>Asset</summary>
		AssetEntity,
		///<summary>AssetDetail</summary>
		AssetDetailEntity,
		///<summary>AssetExportVoucher</summary>
		AssetExportVoucherEntity,
		///<summary>AssetLedger</summary>
		AssetLedgerEntity,
		///<summary>AssetTracking</summary>
		AssetTrackingEntity,
		///<summary>AssetTrackingDepreciation</summary>
		AssetTrackingDepreciationEntity,
		///<summary>BusinessResultItem</summary>
		BusinessResultItemEntity,
		///<summary>CashFlowBalance</summary>
		CashFlowBalanceEntity,
		///<summary>CashFlowCategory</summary>
		CashFlowCategoryEntity,
		///<summary>CashFlowItem</summary>
		CashFlowItemEntity,
		///<summary>CashFlowPreviousPeriod</summary>
		CashFlowPreviousPeriodEntity,
		///<summary>CashFlowYearBalance</summary>
		CashFlowYearBalanceEntity,
		///<summary>Category</summary>
		CategoryEntity,
		///<summary>ChartOfAccount</summary>
		ChartOfAccountEntity,
		///<summary>CostCalculatingBook</summary>
		CostCalculatingBookEntity,
		///<summary>CostCalculatingItem</summary>
		CostCalculatingItemEntity,
		///<summary>CostDetail</summary>
		CostDetailEntity,
		///<summary>CostElement</summary>
		CostElementEntity,
		///<summary>CostLedger</summary>
		CostLedgerEntity,
		///<summary>CostObject</summary>
		CostObjectEntity,
		///<summary>Currency</summary>
		CurrencyEntity,
		///<summary>CurrencyDetail</summary>
		CurrencyDetailEntity,
		///<summary>CurrencyLedger</summary>
		CurrencyLedgerEntity,
		///<summary>CurrencyLiabilityLine</summary>
		CurrencyLiabilityLineEntity,
		///<summary>CustomCostReport</summary>
		CustomCostReportEntity,
		///<summary>CustomCostReportAccount</summary>
		CustomCostReportAccountEntity,
		///<summary>CustomerExportLine</summary>
		CustomerExportLineEntity,
		///<summary>DebtDetail</summary>
		DebtDetailEntity,
		///<summary>DebtLedger</summary>
		DebtLedgerEntity,
		///<summary>DebtReason</summary>
		DebtReasonEntity,
		///<summary>DebtType</summary>
		DebtTypeEntity,
		///<summary>Department</summary>
		DepartmentEntity,
		///<summary>Depreciation</summary>
		DepreciationEntity,
		///<summary>ExchangeRate</summary>
		ExchangeRateEntity,
		///<summary>ExpenseTaxLine</summary>
		ExpenseTaxLineEntity,
		///<summary>FinancialMonth</summary>
		FinancialMonthEntity,
		///<summary>GeneralLedger</summary>
		GeneralLedgerEntity,
		///<summary>Interest</summary>
		InterestEntity,
		///<summary>InterestDetail</summary>
		InterestDetailEntity,
		///<summary>InterestRate</summary>
		InterestRateEntity,
		///<summary>InventoryExportVoucher</summary>
		InventoryExportVoucherEntity,
		///<summary>InventoryItem</summary>
		InventoryItemEntity,
		///<summary>InventoryLedger</summary>
		InventoryLedgerEntity,
		///<summary>InventoryVoucher</summary>
		InventoryVoucherEntity,
		///<summary>InventoryVoucherLine</summary>
		InventoryVoucherLineEntity,
		///<summary>InvestmentDetail</summary>
		InvestmentDetailEntity,
		///<summary>InvestmentLedger</summary>
		InvestmentLedgerEntity,
		///<summary>JournalEntry</summary>
		JournalEntryEntity,
		///<summary>JournalVoucher</summary>
		JournalVoucherEntity,
		///<summary>LiabilityDue</summary>
		LiabilityDueEntity,
		///<summary>MaterialPrice</summary>
		MaterialPriceEntity,
		///<summary>MaterialTaxLine</summary>
		MaterialTaxLineEntity,
		///<summary>Partner</summary>
		PartnerEntity,
		///<summary>PreviousBusinessPeriod</summary>
		PreviousBusinessPeriodEntity,
		///<summary>Reason</summary>
		ReasonEntity,
		///<summary>ReportCategory</summary>
		ReportCategoryEntity,
		///<summary>ReportFormula</summary>
		ReportFormulaEntity,
		///<summary>ReportFormulaAccount</summary>
		ReportFormulaAccountEntity,
		///<summary>ReportItem</summary>
		ReportItemEntity,
		///<summary>ReportSection</summary>
		ReportSectionEntity,
		///<summary>SecurityPolicy</summary>
		SecurityPolicyEntity,
		///<summary>Source</summary>
		SourceEntity,
		///<summary>SpecialValue</summary>
		SpecialValueEntity,
		///<summary>Stock</summary>
		StockEntity,
		///<summary>StockType</summary>
		StockTypeEntity,
		///<summary>SystemUser</summary>
		SystemUserEntity,
		///<summary>TaxObligation</summary>
		TaxObligationEntity,
		///<summary>TaxObligationItem</summary>
		TaxObligationItemEntity,
		///<summary>TaxRate</summary>
		TaxRateEntity,
		///<summary>TrialBalance</summary>
		TrialBalanceEntity,
		///<summary>UserAccount</summary>
		UserAccountEntity,
		///<summary>Vat3TaxItem</summary>
		Vat3TaxItemEntity,
		///<summary>VatDeclareItem</summary>
		VatDeclareItemEntity,
		///<summary>VatEntry</summary>
		VatEntryEntity,
		///<summary>Warehouse</summary>
		WarehouseEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

