//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AccountCostCalculatingItem'.<br/><br/></summary>
	[Serializable]
	public partial class AccountCostCalculatingItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CostCalculatingItemEntity _costCalculatingItem;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AccountCostCalculatingItemEntityStaticMetaData _staticMetaData = new AccountCostCalculatingItemEntityStaticMetaData();
		private static AccountCostCalculatingItemRelations _relationsFactory = new AccountCostCalculatingItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CostCalculatingItem</summary>
			public static readonly string CostCalculatingItem = "CostCalculatingItem";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AccountCostCalculatingItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AccountCostCalculatingItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("AccountCostCalculatingItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.AccountCostCalculatingItemEntity, typeof(AccountCostCalculatingItemEntity), typeof(AccountCostCalculatingItemEntityFactory), false);
				AddNavigatorMetaData<AccountCostCalculatingItemEntity, CostCalculatingItemEntity>("CostCalculatingItem", "AccountCostCalculatingItems", (a, b) => a._costCalculatingItem = b, a => a._costCalculatingItem, (a, b) => a.CostCalculatingItem = b, DataAccess.RelationClasses.StaticAccountCostCalculatingItemRelations.CostCalculatingItemEntityUsingCostCalculatingItemIdStatic, ()=>new AccountCostCalculatingItemRelations().CostCalculatingItemEntityUsingCostCalculatingItemId, null, new int[] { (int)AccountCostCalculatingItemFieldIndex.CostCalculatingItemId }, null, true, (int)DataAccess.EntityType.CostCalculatingItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AccountCostCalculatingItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public AccountCostCalculatingItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AccountCostCalculatingItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AccountCostCalculatingItemEntity</param>
		public AccountCostCalculatingItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AccountCostCalculatingItem which data should be fetched into this AccountCostCalculatingItem object</param>
		public AccountCostCalculatingItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AccountCostCalculatingItem which data should be fetched into this AccountCostCalculatingItem object</param>
		/// <param name="validator">The custom validator object for this AccountCostCalculatingItemEntity</param>
		public AccountCostCalculatingItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AccountCostCalculatingItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CostCalculatingItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCostCalculatingItem() { return CreateRelationInfoForNavigator("CostCalculatingItem"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AccountCostCalculatingItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AccountCostCalculatingItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CostCalculatingItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCostCalculatingItem { get { return _staticMetaData.GetPrefetchPathElement("CostCalculatingItem", CommonEntityBase.CreateEntityCollection<CostCalculatingItemEntity>()); } }

		/// <summary>The AccountId property of the Entity AccountCostCalculatingItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountCostCalculatingItem"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AccountId
		{
			get { return (System.String)GetValue((int)AccountCostCalculatingItemFieldIndex.AccountId, true); }
			set { SetValue((int)AccountCostCalculatingItemFieldIndex.AccountId, value); }
		}

		/// <summary>The CostCalculatingItemId property of the Entity AccountCostCalculatingItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountCostCalculatingItem"."CostCalculatingItemId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CostCalculatingItemId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AccountCostCalculatingItemFieldIndex.CostCalculatingItemId, false); }
			set { SetValue((int)AccountCostCalculatingItemFieldIndex.CostCalculatingItemId, value); }
		}

		/// <summary>The Id property of the Entity AccountCostCalculatingItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountCostCalculatingItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AccountCostCalculatingItemFieldIndex.Id, true); }
			set { SetValue((int)AccountCostCalculatingItemFieldIndex.Id, value); }
		}

		/// <summary>The IsAdd property of the Entity AccountCostCalculatingItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountCostCalculatingItem"."IsAdd".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsAdd
		{
			get { return (System.Boolean)GetValue((int)AccountCostCalculatingItemFieldIndex.IsAdd, true); }
			set { SetValue((int)AccountCostCalculatingItemFieldIndex.IsAdd, value); }
		}

		/// <summary>The Method property of the Entity AccountCostCalculatingItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountCostCalculatingItem"."Method".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Method
		{
			get { return (Nullable<System.Int16>)GetValue((int)AccountCostCalculatingItemFieldIndex.Method, false); }
			set { SetValue((int)AccountCostCalculatingItemFieldIndex.Method, value); }
		}

		/// <summary>Gets / sets related entity of type 'CostCalculatingItemEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CostCalculatingItemEntity CostCalculatingItem
		{
			get { return _costCalculatingItem; }
			set { SetSingleRelatedEntityNavigator(value, "CostCalculatingItem"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum AccountCostCalculatingItemFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>CostCalculatingItemId. </summary>
		CostCalculatingItemId,
		///<summary>Id. </summary>
		Id,
		///<summary>IsAdd. </summary>
		IsAdd,
		///<summary>Method. </summary>
		Method,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AccountCostCalculatingItem. </summary>
	public partial class AccountCostCalculatingItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AccountCostCalculatingItemEntity and CostCalculatingItemEntity over the m:1 relation they have, using the relation between the fields: AccountCostCalculatingItem.CostCalculatingItemId - CostCalculatingItem.Id</summary>
		public virtual IEntityRelation CostCalculatingItemEntityUsingCostCalculatingItemId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CostCalculatingItem", false, new[] { CostCalculatingItemFields.Id, AccountCostCalculatingItemFields.CostCalculatingItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAccountCostCalculatingItemRelations
	{
		internal static readonly IEntityRelation CostCalculatingItemEntityUsingCostCalculatingItemIdStatic = new AccountCostCalculatingItemRelations().CostCalculatingItemEntityUsingCostCalculatingItemId;

		/// <summary>CTor</summary>
		static StaticAccountCostCalculatingItemRelations() { }
	}
}
