//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AccountVat3Item'.<br/><br/></summary>
	[Serializable]
	public partial class AccountVat3ItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private Vat3TaxItemEntity _vat3TaxItem;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AccountVat3ItemEntityStaticMetaData _staticMetaData = new AccountVat3ItemEntityStaticMetaData();
		private static AccountVat3ItemRelations _relationsFactory = new AccountVat3ItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Vat3TaxItem</summary>
			public static readonly string Vat3TaxItem = "Vat3TaxItem";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AccountVat3ItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AccountVat3ItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("AccountVat3ItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.AccountVat3ItemEntity, typeof(AccountVat3ItemEntity), typeof(AccountVat3ItemEntityFactory), false);
				AddNavigatorMetaData<AccountVat3ItemEntity, Vat3TaxItemEntity>("Vat3TaxItem", "AccountVat3Items", (a, b) => a._vat3TaxItem = b, a => a._vat3TaxItem, (a, b) => a.Vat3TaxItem = b, DataAccess.RelationClasses.StaticAccountVat3ItemRelations.Vat3TaxItemEntityUsingVat3TaxItemIdStatic, ()=>new AccountVat3ItemRelations().Vat3TaxItemEntityUsingVat3TaxItemId, null, new int[] { (int)AccountVat3ItemFieldIndex.Vat3TaxItemId }, null, true, (int)DataAccess.EntityType.Vat3TaxItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AccountVat3ItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public AccountVat3ItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AccountVat3ItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AccountVat3ItemEntity</param>
		public AccountVat3ItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AccountVat3Item which data should be fetched into this AccountVat3Item object</param>
		public AccountVat3ItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AccountVat3Item which data should be fetched into this AccountVat3Item object</param>
		/// <param name="validator">The custom validator object for this AccountVat3ItemEntity</param>
		public AccountVat3ItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AccountVat3ItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Vat3TaxItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoVat3TaxItem() { return CreateRelationInfoForNavigator("Vat3TaxItem"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AccountVat3ItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AccountVat3ItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Vat3TaxItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathVat3TaxItem { get { return _staticMetaData.GetPrefetchPathElement("Vat3TaxItem", CommonEntityBase.CreateEntityCollection<Vat3TaxItemEntity>()); } }

		/// <summary>The AccountId property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AccountId
		{
			get { return (System.String)GetValue((int)AccountVat3ItemFieldIndex.AccountId, true); }
			set { SetValue((int)AccountVat3ItemFieldIndex.AccountId, value); }
		}

		/// <summary>The CounterAccountId property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."CounterAccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CounterAccountId
		{
			get { return (System.String)GetValue((int)AccountVat3ItemFieldIndex.CounterAccountId, true); }
			set { SetValue((int)AccountVat3ItemFieldIndex.CounterAccountId, value); }
		}

		/// <summary>The Id property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AccountVat3ItemFieldIndex.Id, true); }
			set { SetValue((int)AccountVat3ItemFieldIndex.Id, value); }
		}

		/// <summary>The IsAdd property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."IsAdd".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsAdd
		{
			get { return (System.Boolean)GetValue((int)AccountVat3ItemFieldIndex.IsAdd, true); }
			set { SetValue((int)AccountVat3ItemFieldIndex.IsAdd, value); }
		}

		/// <summary>The Method property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."Method".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Method
		{
			get { return (Nullable<System.Int16>)GetValue((int)AccountVat3ItemFieldIndex.Method, false); }
			set { SetValue((int)AccountVat3ItemFieldIndex.Method, value); }
		}

		/// <summary>The Vat3TaxItemId property of the Entity AccountVat3Item<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AccountVat3Item"."Vat3TaxItemId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Vat3TaxItemId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AccountVat3ItemFieldIndex.Vat3TaxItemId, false); }
			set { SetValue((int)AccountVat3ItemFieldIndex.Vat3TaxItemId, value); }
		}

		/// <summary>Gets / sets related entity of type 'Vat3TaxItemEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual Vat3TaxItemEntity Vat3TaxItem
		{
			get { return _vat3TaxItem; }
			set { SetSingleRelatedEntityNavigator(value, "Vat3TaxItem"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum AccountVat3ItemFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>CounterAccountId. </summary>
		CounterAccountId,
		///<summary>Id. </summary>
		Id,
		///<summary>IsAdd. </summary>
		IsAdd,
		///<summary>Method. </summary>
		Method,
		///<summary>Vat3TaxItemId. </summary>
		Vat3TaxItemId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AccountVat3Item. </summary>
	public partial class AccountVat3ItemRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AccountVat3ItemEntity and Vat3TaxItemEntity over the m:1 relation they have, using the relation between the fields: AccountVat3Item.Vat3TaxItemId - Vat3TaxItem.Id</summary>
		public virtual IEntityRelation Vat3TaxItemEntityUsingVat3TaxItemId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Vat3TaxItem", false, new[] { Vat3TaxItemFields.Id, AccountVat3ItemFields.Vat3TaxItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAccountVat3ItemRelations
	{
		internal static readonly IEntityRelation Vat3TaxItemEntityUsingVat3TaxItemIdStatic = new AccountVat3ItemRelations().Vat3TaxItemEntityUsingVat3TaxItemId;

		/// <summary>CTor</summary>
		static StaticAccountVat3ItemRelations() { }
	}
}
