//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AssetLedger'.<br/><br/></summary>
	[Serializable]
	public partial class AssetLedgerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AssetLedgerEntityStaticMetaData _staticMetaData = new AssetLedgerEntityStaticMetaData();
		private static AssetLedgerRelations _relationsFactory = new AssetLedgerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AssetLedgerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AssetLedgerEntityStaticMetaData()
			{
				SetEntityCoreInfo("AssetLedgerEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.AssetLedgerEntity, typeof(AssetLedgerEntity), typeof(AssetLedgerEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static AssetLedgerEntity()
		{
		}

		/// <summary> CTor</summary>
		public AssetLedgerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AssetLedgerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AssetLedgerEntity</param>
		public AssetLedgerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AssetLedger which data should be fetched into this AssetLedger object</param>
		public AssetLedgerEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for AssetLedger which data should be fetched into this AssetLedger object</param>
		/// <param name="validator">The custom validator object for this AssetLedgerEntity</param>
		public AssetLedgerEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AssetLedgerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AssetLedgerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AssetLedgerRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Camount property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Camount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Camount
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Camount, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Camount, value); }
		}

		/// <summary>The Contents property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Contents".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Contents
		{
			get { return (System.String)GetValue((int)AssetLedgerFieldIndex.Contents, true); }
			set { SetValue((int)AssetLedgerFieldIndex.Contents, value); }
		}

		/// <summary>The Cprice property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Cprice".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Cprice
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Cprice, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Cprice, value); }
		}

		/// <summary>The Cquantity property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Cquantity".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Cquantity
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Cquantity, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Cquantity, value); }
		}

		/// <summary>The Damount property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Damount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Damount
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Damount, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Damount, value); }
		}

		/// <summary>The Dprice property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Dprice".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Dprice
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Dprice, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Dprice, value); }
		}

		/// <summary>The Dquantity property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Dquantity".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Dquantity
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Dquantity, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Dquantity, value); }
		}

		/// <summary>The Endamount property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Endamount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endamount
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Endamount, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Endamount, value); }
		}

		/// <summary>The Endqty property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Endqty".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endqty
		{
			get { return (Nullable<System.Double>)GetValue((int)AssetLedgerFieldIndex.Endqty, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Endqty, value); }
		}

		/// <summary>The Flag property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Flag".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Flag
		{
			get { return (Nullable<System.Int32>)GetValue((int)AssetLedgerFieldIndex.Flag, false); }
			set { SetValue((int)AssetLedgerFieldIndex.Flag, value); }
		}

		/// <summary>The Id property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)AssetLedgerFieldIndex.Id, true); }
			set { SetValue((int)AssetLedgerFieldIndex.Id, value); }
		}

		/// <summary>The JournalVoucherId property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."JournalVoucherId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> JournalVoucherId
		{
			get { return (Nullable<System.Int32>)GetValue((int)AssetLedgerFieldIndex.JournalVoucherId, false); }
			set { SetValue((int)AssetLedgerFieldIndex.JournalVoucherId, value); }
		}

		/// <summary>The VoucherDate property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."VoucherDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> VoucherDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)AssetLedgerFieldIndex.VoucherDate, false); }
			set { SetValue((int)AssetLedgerFieldIndex.VoucherDate, value); }
		}

		/// <summary>The VoucherNo property of the Entity AssetLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "AssetLedger"."VoucherNo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VoucherNo
		{
			get { return (System.String)GetValue((int)AssetLedgerFieldIndex.VoucherNo, true); }
			set { SetValue((int)AssetLedgerFieldIndex.VoucherNo, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum AssetLedgerFieldIndex
	{
		///<summary>Camount. </summary>
		Camount,
		///<summary>Contents. </summary>
		Contents,
		///<summary>Cprice. </summary>
		Cprice,
		///<summary>Cquantity. </summary>
		Cquantity,
		///<summary>Damount. </summary>
		Damount,
		///<summary>Dprice. </summary>
		Dprice,
		///<summary>Dquantity. </summary>
		Dquantity,
		///<summary>Endamount. </summary>
		Endamount,
		///<summary>Endqty. </summary>
		Endqty,
		///<summary>Flag. </summary>
		Flag,
		///<summary>Id. </summary>
		Id,
		///<summary>JournalVoucherId. </summary>
		JournalVoucherId,
		///<summary>VoucherDate. </summary>
		VoucherDate,
		///<summary>VoucherNo. </summary>
		VoucherNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AssetLedger. </summary>
	public partial class AssetLedgerRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAssetLedgerRelations
	{

		/// <summary>CTor</summary>
		static StaticAssetLedgerRelations() { }
	}
}
