//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'BusinessResultItem'.<br/><br/></summary>
	[Serializable]
	public partial class BusinessResultItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AccountBusinessResultEntity> _accountBusinessResults;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static BusinessResultItemEntityStaticMetaData _staticMetaData = new BusinessResultItemEntityStaticMetaData();
		private static BusinessResultItemRelations _relationsFactory = new BusinessResultItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AccountBusinessResults</summary>
			public static readonly string AccountBusinessResults = "AccountBusinessResults";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class BusinessResultItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public BusinessResultItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("BusinessResultItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.BusinessResultItemEntity, typeof(BusinessResultItemEntity), typeof(BusinessResultItemEntityFactory), false);
				AddNavigatorMetaData<BusinessResultItemEntity, EntityCollection<AccountBusinessResultEntity>>("AccountBusinessResults", a => a._accountBusinessResults, (a, b) => a._accountBusinessResults = b, a => a.AccountBusinessResults, () => new BusinessResultItemRelations().AccountBusinessResultEntityUsingBusinessResultItemId, typeof(AccountBusinessResultEntity), (int)DataAccess.EntityType.AccountBusinessResultEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static BusinessResultItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public BusinessResultItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public BusinessResultItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this BusinessResultItemEntity</param>
		public BusinessResultItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for BusinessResultItem which data should be fetched into this BusinessResultItem object</param>
		public BusinessResultItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for BusinessResultItem which data should be fetched into this BusinessResultItem object</param>
		/// <param name="validator">The custom validator object for this BusinessResultItemEntity</param>
		public BusinessResultItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected BusinessResultItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AccountBusinessResult' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccountBusinessResults() { return CreateRelationInfoForNavigator("AccountBusinessResults"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this BusinessResultItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static BusinessResultItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AccountBusinessResult' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccountBusinessResults { get { return _staticMetaData.GetPrefetchPathElement("AccountBusinessResults", CommonEntityBase.CreateEntityCollection<AccountBusinessResultEntity>()); } }

		/// <summary>The Code property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)BusinessResultItemFieldIndex.Code, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.Code, value); }
		}

		/// <summary>The Id property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)BusinessResultItemFieldIndex.Id, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.Id, value); }
		}

		/// <summary>The Illustration property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."Illustration".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Illustration
		{
			get { return (System.String)GetValue((int)BusinessResultItemFieldIndex.Illustration, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.Illustration, value); }
		}

		/// <summary>The IsBold property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."IsBold".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsBold
		{
			get { return (System.Boolean)GetValue((int)BusinessResultItemFieldIndex.IsBold, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.IsBold, value); }
		}

		/// <summary>The IsDecrease property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."IsDecrease".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsDecrease
		{
			get { return (System.Boolean)GetValue((int)BusinessResultItemFieldIndex.IsDecrease, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.IsDecrease, value); }
		}

		/// <summary>The IsItalic property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."IsItalic".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsItalic
		{
			get { return (System.Boolean)GetValue((int)BusinessResultItemFieldIndex.IsItalic, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.IsItalic, value); }
		}

		/// <summary>The ItemName property of the Entity BusinessResultItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "BusinessResultItem"."ItemName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemName
		{
			get { return (System.String)GetValue((int)BusinessResultItemFieldIndex.ItemName, true); }
			set { SetValue((int)BusinessResultItemFieldIndex.ItemName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AccountBusinessResultEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AccountBusinessResultEntity))]
		public virtual EntityCollection<AccountBusinessResultEntity> AccountBusinessResults { get { return GetOrCreateEntityCollection<AccountBusinessResultEntity, AccountBusinessResultEntityFactory>("BusinessResultItem", true, false, ref _accountBusinessResults); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum BusinessResultItemFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>Id. </summary>
		Id,
		///<summary>Illustration. </summary>
		Illustration,
		///<summary>IsBold. </summary>
		IsBold,
		///<summary>IsDecrease. </summary>
		IsDecrease,
		///<summary>IsItalic. </summary>
		IsItalic,
		///<summary>ItemName. </summary>
		ItemName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: BusinessResultItem. </summary>
	public partial class BusinessResultItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between BusinessResultItemEntity and AccountBusinessResultEntity over the 1:n relation they have, using the relation between the fields: BusinessResultItem.Id - AccountBusinessResult.BusinessResultItemId</summary>
		public virtual IEntityRelation AccountBusinessResultEntityUsingBusinessResultItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AccountBusinessResults", true, new[] { BusinessResultItemFields.Id, AccountBusinessResultFields.BusinessResultItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticBusinessResultItemRelations
	{
		internal static readonly IEntityRelation AccountBusinessResultEntityUsingBusinessResultItemIdStatic = new BusinessResultItemRelations().AccountBusinessResultEntityUsingBusinessResultItemId;

		/// <summary>CTor</summary>
		static StaticBusinessResultItemRelations() { }
	}
}
