//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CashFlowItem'.<br/><br/></summary>
	[Serializable]
	public partial class CashFlowItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AccountCashFlowItemEntity> _accountCashFlowItems;
		private CashFlowCategoryEntity _cashFlowCategory;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CashFlowItemEntityStaticMetaData _staticMetaData = new CashFlowItemEntityStaticMetaData();
		private static CashFlowItemRelations _relationsFactory = new CashFlowItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CashFlowCategory</summary>
			public static readonly string CashFlowCategory = "CashFlowCategory";
			/// <summary>Member name AccountCashFlowItems</summary>
			public static readonly string AccountCashFlowItems = "AccountCashFlowItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CashFlowItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CashFlowItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("CashFlowItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CashFlowItemEntity, typeof(CashFlowItemEntity), typeof(CashFlowItemEntityFactory), false);
				AddNavigatorMetaData<CashFlowItemEntity, EntityCollection<AccountCashFlowItemEntity>>("AccountCashFlowItems", a => a._accountCashFlowItems, (a, b) => a._accountCashFlowItems = b, a => a.AccountCashFlowItems, () => new CashFlowItemRelations().AccountCashFlowItemEntityUsingCashFlowItemId, typeof(AccountCashFlowItemEntity), (int)DataAccess.EntityType.AccountCashFlowItemEntity);
				AddNavigatorMetaData<CashFlowItemEntity, CashFlowCategoryEntity>("CashFlowCategory", "CashFlowItems", (a, b) => a._cashFlowCategory = b, a => a._cashFlowCategory, (a, b) => a.CashFlowCategory = b, DataAccess.RelationClasses.StaticCashFlowItemRelations.CashFlowCategoryEntityUsingCashFlowCategoryIdStatic, ()=>new CashFlowItemRelations().CashFlowCategoryEntityUsingCashFlowCategoryId, null, new int[] { (int)CashFlowItemFieldIndex.CashFlowCategoryId }, null, true, (int)DataAccess.EntityType.CashFlowCategoryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CashFlowItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public CashFlowItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CashFlowItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CashFlowItemEntity</param>
		public CashFlowItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CashFlowItem which data should be fetched into this CashFlowItem object</param>
		public CashFlowItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CashFlowItem which data should be fetched into this CashFlowItem object</param>
		/// <param name="validator">The custom validator object for this CashFlowItemEntity</param>
		public CashFlowItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CashFlowItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AccountCashFlowItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccountCashFlowItems() { return CreateRelationInfoForNavigator("AccountCashFlowItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CashFlowCategory' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCashFlowCategory() { return CreateRelationInfoForNavigator("CashFlowCategory"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CashFlowItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CashFlowItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AccountCashFlowItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccountCashFlowItems { get { return _staticMetaData.GetPrefetchPathElement("AccountCashFlowItems", CommonEntityBase.CreateEntityCollection<AccountCashFlowItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CashFlowCategory' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCashFlowCategory { get { return _staticMetaData.GetPrefetchPathElement("CashFlowCategory", CommonEntityBase.CreateEntityCollection<CashFlowCategoryEntity>()); } }

		/// <summary>The CashFlowCategoryId property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."CashFlowCategoryId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CashFlowCategoryId
		{
			get { return (Nullable<System.Int32>)GetValue((int)CashFlowItemFieldIndex.CashFlowCategoryId, false); }
			set { SetValue((int)CashFlowItemFieldIndex.CashFlowCategoryId, value); }
		}

		/// <summary>The Code property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)CashFlowItemFieldIndex.Code, true); }
			set { SetValue((int)CashFlowItemFieldIndex.Code, value); }
		}

		/// <summary>The Dbcr property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."Dbcr".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Dbcr
		{
			get { return (System.Boolean)GetValue((int)CashFlowItemFieldIndex.Dbcr, true); }
			set { SetValue((int)CashFlowItemFieldIndex.Dbcr, value); }
		}

		/// <summary>The Id property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CashFlowItemFieldIndex.Id, true); }
			set { SetValue((int)CashFlowItemFieldIndex.Id, value); }
		}

		/// <summary>The Illustration property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."Illustration".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Illustration
		{
			get { return (System.String)GetValue((int)CashFlowItemFieldIndex.Illustration, true); }
			set { SetValue((int)CashFlowItemFieldIndex.Illustration, value); }
		}

		/// <summary>The IsBold property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."IsBold".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsBold
		{
			get { return (System.Boolean)GetValue((int)CashFlowItemFieldIndex.IsBold, true); }
			set { SetValue((int)CashFlowItemFieldIndex.IsBold, value); }
		}

		/// <summary>The IsItalic property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."IsItalic".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsItalic
		{
			get { return (System.Boolean)GetValue((int)CashFlowItemFieldIndex.IsItalic, true); }
			set { SetValue((int)CashFlowItemFieldIndex.IsItalic, value); }
		}

		/// <summary>The ItemName property of the Entity CashFlowItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowItem"."ItemName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemName
		{
			get { return (System.String)GetValue((int)CashFlowItemFieldIndex.ItemName, true); }
			set { SetValue((int)CashFlowItemFieldIndex.ItemName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AccountCashFlowItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AccountCashFlowItemEntity))]
		public virtual EntityCollection<AccountCashFlowItemEntity> AccountCashFlowItems { get { return GetOrCreateEntityCollection<AccountCashFlowItemEntity, AccountCashFlowItemEntityFactory>("CashFlowItem", true, false, ref _accountCashFlowItems); } }

		/// <summary>Gets / sets related entity of type 'CashFlowCategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CashFlowCategoryEntity CashFlowCategory
		{
			get { return _cashFlowCategory; }
			set { SetSingleRelatedEntityNavigator(value, "CashFlowCategory"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CashFlowItemFieldIndex
	{
		///<summary>CashFlowCategoryId. </summary>
		CashFlowCategoryId,
		///<summary>Code. </summary>
		Code,
		///<summary>Dbcr. </summary>
		Dbcr,
		///<summary>Id. </summary>
		Id,
		///<summary>Illustration. </summary>
		Illustration,
		///<summary>IsBold. </summary>
		IsBold,
		///<summary>IsItalic. </summary>
		IsItalic,
		///<summary>ItemName. </summary>
		ItemName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CashFlowItem. </summary>
	public partial class CashFlowItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CashFlowItemEntity and AccountCashFlowItemEntity over the 1:n relation they have, using the relation between the fields: CashFlowItem.Id - AccountCashFlowItem.CashFlowItemId</summary>
		public virtual IEntityRelation AccountCashFlowItemEntityUsingCashFlowItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AccountCashFlowItems", true, new[] { CashFlowItemFields.Id, AccountCashFlowItemFields.CashFlowItemId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CashFlowItemEntity and CashFlowCategoryEntity over the m:1 relation they have, using the relation between the fields: CashFlowItem.CashFlowCategoryId - CashFlowCategory.Id</summary>
		public virtual IEntityRelation CashFlowCategoryEntityUsingCashFlowCategoryId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CashFlowCategory", false, new[] { CashFlowCategoryFields.Id, CashFlowItemFields.CashFlowCategoryId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCashFlowItemRelations
	{
		internal static readonly IEntityRelation AccountCashFlowItemEntityUsingCashFlowItemIdStatic = new CashFlowItemRelations().AccountCashFlowItemEntityUsingCashFlowItemId;
		internal static readonly IEntityRelation CashFlowCategoryEntityUsingCashFlowCategoryIdStatic = new CashFlowItemRelations().CashFlowCategoryEntityUsingCashFlowCategoryId;

		/// <summary>CTor</summary>
		static StaticCashFlowItemRelations() { }
	}
}
