//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CashFlowPreviousPeriod'.<br/><br/></summary>
	[Serializable]
	public partial class CashFlowPreviousPeriodEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CashFlowCategoryEntity _cashFlowCategory;
		private ReportFormulaEntity _reportFormula;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CashFlowPreviousPeriodEntityStaticMetaData _staticMetaData = new CashFlowPreviousPeriodEntityStaticMetaData();
		private static CashFlowPreviousPeriodRelations _relationsFactory = new CashFlowPreviousPeriodRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CashFlowCategory</summary>
			public static readonly string CashFlowCategory = "CashFlowCategory";
			/// <summary>Member name ReportFormula</summary>
			public static readonly string ReportFormula = "ReportFormula";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CashFlowPreviousPeriodEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CashFlowPreviousPeriodEntityStaticMetaData()
			{
				SetEntityCoreInfo("CashFlowPreviousPeriodEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CashFlowPreviousPeriodEntity, typeof(CashFlowPreviousPeriodEntity), typeof(CashFlowPreviousPeriodEntityFactory), false);
				AddNavigatorMetaData<CashFlowPreviousPeriodEntity, CashFlowCategoryEntity>("CashFlowCategory", "CashFlowPreviousPeriods", (a, b) => a._cashFlowCategory = b, a => a._cashFlowCategory, (a, b) => a.CashFlowCategory = b, DataAccess.RelationClasses.StaticCashFlowPreviousPeriodRelations.CashFlowCategoryEntityUsingCashFlowIdStatic, ()=>new CashFlowPreviousPeriodRelations().CashFlowCategoryEntityUsingCashFlowId, null, new int[] { (int)CashFlowPreviousPeriodFieldIndex.CashFlowId }, null, true, (int)DataAccess.EntityType.CashFlowCategoryEntity);
				AddNavigatorMetaData<CashFlowPreviousPeriodEntity, ReportFormulaEntity>("ReportFormula", "CashFlowPreviousPeriods", (a, b) => a._reportFormula = b, a => a._reportFormula, (a, b) => a.ReportFormula = b, DataAccess.RelationClasses.StaticCashFlowPreviousPeriodRelations.ReportFormulaEntityUsingItemsIdStatic, ()=>new CashFlowPreviousPeriodRelations().ReportFormulaEntityUsingItemsId, null, new int[] { (int)CashFlowPreviousPeriodFieldIndex.ItemsId }, null, true, (int)DataAccess.EntityType.ReportFormulaEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CashFlowPreviousPeriodEntity()
		{
		}

		/// <summary> CTor</summary>
		public CashFlowPreviousPeriodEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CashFlowPreviousPeriodEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CashFlowPreviousPeriodEntity</param>
		public CashFlowPreviousPeriodEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="code">PK value for CashFlowPreviousPeriod which data should be fetched into this CashFlowPreviousPeriod object</param>
		public CashFlowPreviousPeriodEntity(System.String code) : this(code, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="code">PK value for CashFlowPreviousPeriod which data should be fetched into this CashFlowPreviousPeriod object</param>
		/// <param name="validator">The custom validator object for this CashFlowPreviousPeriodEntity</param>
		public CashFlowPreviousPeriodEntity(System.String code, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Code = code;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CashFlowPreviousPeriodEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CashFlowCategory' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCashFlowCategory() { return CreateRelationInfoForNavigator("CashFlowCategory"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ReportFormula' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReportFormula() { return CreateRelationInfoForNavigator("ReportFormula"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CashFlowPreviousPeriodEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CashFlowPreviousPeriodRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CashFlowCategory' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCashFlowCategory { get { return _staticMetaData.GetPrefetchPathElement("CashFlowCategory", CommonEntityBase.CreateEntityCollection<CashFlowCategoryEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ReportFormula' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReportFormula { get { return _staticMetaData.GetPrefetchPathElement("ReportFormula", CommonEntityBase.CreateEntityCollection<ReportFormulaEntity>()); } }

		/// <summary>The Amount property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."Amount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Amount
		{
			get { return (Nullable<System.Double>)GetValue((int)CashFlowPreviousPeriodFieldIndex.Amount, false); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.Amount, value); }
		}

		/// <summary>The Bold property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."Bold".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Bold
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.Bold, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.Bold, value); }
		}

		/// <summary>The CashFlowId property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."CashFlowId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CashFlowId
		{
			get { return (Nullable<System.Int32>)GetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowId, false); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowId, value); }
		}

		/// <summary>The CashFlowName property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."CashFlowName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CashFlowName
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowName, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowName, value); }
		}

		/// <summary>The CashFlowNameRepeate property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."CashFlowNameRepeate".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CashFlowNameRepeate
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowNameRepeate, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.CashFlowNameRepeate, value); }
		}

		/// <summary>The Code property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.Code, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.Code, value); }
		}

		/// <summary>The Italic property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."Italic".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Italic
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.Italic, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.Italic, value); }
		}

		/// <summary>The ItemsId property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."ItemsId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ItemsId
		{
			get { return (Nullable<System.Int32>)GetValue((int)CashFlowPreviousPeriodFieldIndex.ItemsId, false); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.ItemsId, value); }
		}

		/// <summary>The ItemsName property of the Entity CashFlowPreviousPeriod<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowPreviousPeriod"."ItemsName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemsName
		{
			get { return (System.String)GetValue((int)CashFlowPreviousPeriodFieldIndex.ItemsName, true); }
			set { SetValue((int)CashFlowPreviousPeriodFieldIndex.ItemsName, value); }
		}

		/// <summary>Gets / sets related entity of type 'CashFlowCategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CashFlowCategoryEntity CashFlowCategory
		{
			get { return _cashFlowCategory; }
			set { SetSingleRelatedEntityNavigator(value, "CashFlowCategory"); }
		}

		/// <summary>Gets / sets related entity of type 'ReportFormulaEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ReportFormulaEntity ReportFormula
		{
			get { return _reportFormula; }
			set { SetSingleRelatedEntityNavigator(value, "ReportFormula"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CashFlowPreviousPeriodFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>Bold. </summary>
		Bold,
		///<summary>CashFlowId. </summary>
		CashFlowId,
		///<summary>CashFlowName. </summary>
		CashFlowName,
		///<summary>CashFlowNameRepeate. </summary>
		CashFlowNameRepeate,
		///<summary>Code. </summary>
		Code,
		///<summary>Italic. </summary>
		Italic,
		///<summary>ItemsId. </summary>
		ItemsId,
		///<summary>ItemsName. </summary>
		ItemsName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CashFlowPreviousPeriod. </summary>
	public partial class CashFlowPreviousPeriodRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between CashFlowPreviousPeriodEntity and CashFlowCategoryEntity over the m:1 relation they have, using the relation between the fields: CashFlowPreviousPeriod.CashFlowId - CashFlowCategory.Id</summary>
		public virtual IEntityRelation CashFlowCategoryEntityUsingCashFlowId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CashFlowCategory", false, new[] { CashFlowCategoryFields.Id, CashFlowPreviousPeriodFields.CashFlowId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CashFlowPreviousPeriodEntity and ReportFormulaEntity over the m:1 relation they have, using the relation between the fields: CashFlowPreviousPeriod.ItemsId - ReportFormula.Id</summary>
		public virtual IEntityRelation ReportFormulaEntityUsingItemsId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ReportFormula", false, new[] { ReportFormulaFields.Id, CashFlowPreviousPeriodFields.ItemsId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCashFlowPreviousPeriodRelations
	{
		internal static readonly IEntityRelation CashFlowCategoryEntityUsingCashFlowIdStatic = new CashFlowPreviousPeriodRelations().CashFlowCategoryEntityUsingCashFlowId;
		internal static readonly IEntityRelation ReportFormulaEntityUsingItemsIdStatic = new CashFlowPreviousPeriodRelations().ReportFormulaEntityUsingItemsId;

		/// <summary>CTor</summary>
		static StaticCashFlowPreviousPeriodRelations() { }
	}
}
