//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CashFlowBalance'.<br/><br/></summary>
	[Serializable]
	public partial class CashFlowBalanceEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CashFlowBalanceEntityStaticMetaData _staticMetaData = new CashFlowBalanceEntityStaticMetaData();
		private static CashFlowBalanceRelations _relationsFactory = new CashFlowBalanceRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CashFlowBalanceEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CashFlowBalanceEntityStaticMetaData()
			{
				SetEntityCoreInfo("CashFlowBalanceEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CashFlowBalanceEntity, typeof(CashFlowBalanceEntity), typeof(CashFlowBalanceEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static CashFlowBalanceEntity()
		{
		}

		/// <summary> CTor</summary>
		public CashFlowBalanceEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CashFlowBalanceEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CashFlowBalanceEntity</param>
		public CashFlowBalanceEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CashFlowBalance which data should be fetched into this CashFlowBalance object</param>
		public CashFlowBalanceEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CashFlowBalance which data should be fetched into this CashFlowBalance object</param>
		/// <param name="validator">The custom validator object for this CashFlowBalanceEntity</param>
		public CashFlowBalanceEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CashFlowBalanceEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CashFlowBalanceEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CashFlowBalanceRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity CashFlowBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowBalance"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CashFlowBalanceFieldIndex.Id, true); }
			set { SetValue((int)CashFlowBalanceFieldIndex.Id, value); }
		}

		/// <summary>The Prevbeginbalance property of the Entity CashFlowBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowBalance"."Prevbeginbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Prevbeginbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)CashFlowBalanceFieldIndex.Prevbeginbalance, false); }
			set { SetValue((int)CashFlowBalanceFieldIndex.Prevbeginbalance, value); }
		}

		/// <summary>The Prevendbalance property of the Entity CashFlowBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowBalance"."Prevendbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Prevendbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)CashFlowBalanceFieldIndex.Prevendbalance, false); }
			set { SetValue((int)CashFlowBalanceFieldIndex.Prevendbalance, value); }
		}

		/// <summary>The Thisbeginbalance property of the Entity CashFlowBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowBalance"."Thisbeginbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Thisbeginbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)CashFlowBalanceFieldIndex.Thisbeginbalance, false); }
			set { SetValue((int)CashFlowBalanceFieldIndex.Thisbeginbalance, value); }
		}

		/// <summary>The Thisendbalance property of the Entity CashFlowBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CashFlowBalance"."Thisendbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Thisendbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)CashFlowBalanceFieldIndex.Thisendbalance, false); }
			set { SetValue((int)CashFlowBalanceFieldIndex.Thisendbalance, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CashFlowBalanceFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Prevbeginbalance. </summary>
		Prevbeginbalance,
		///<summary>Prevendbalance. </summary>
		Prevendbalance,
		///<summary>Thisbeginbalance. </summary>
		Thisbeginbalance,
		///<summary>Thisendbalance. </summary>
		Thisendbalance,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CashFlowBalance. </summary>
	public partial class CashFlowBalanceRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCashFlowBalanceRelations
	{

		/// <summary>CTor</summary>
		static StaticCashFlowBalanceRelations() { }
	}
}
