//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Category'.<br/><br/></summary>
	[Serializable]
	public partial class CategoryEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<InventoryItemEntity> _inventoryItems;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CategoryEntityStaticMetaData _staticMetaData = new CategoryEntityStaticMetaData();
		private static CategoryRelations _relationsFactory = new CategoryRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name InventoryItems</summary>
			public static readonly string InventoryItems = "InventoryItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CategoryEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CategoryEntityStaticMetaData()
			{
				SetEntityCoreInfo("CategoryEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CategoryEntity, typeof(CategoryEntity), typeof(CategoryEntityFactory), false);
				AddNavigatorMetaData<CategoryEntity, EntityCollection<InventoryItemEntity>>("InventoryItems", a => a._inventoryItems, (a, b) => a._inventoryItems = b, a => a.InventoryItems, () => new CategoryRelations().InventoryItemEntityUsingCategoryid, typeof(InventoryItemEntity), (int)DataAccess.EntityType.InventoryItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CategoryEntity()
		{
		}

		/// <summary> CTor</summary>
		public CategoryEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CategoryEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CategoryEntity</param>
		public CategoryEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="categoryid">PK value for Category which data should be fetched into this Category object</param>
		public CategoryEntity(System.String categoryid) : this(categoryid, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="categoryid">PK value for Category which data should be fetched into this Category object</param>
		/// <param name="validator">The custom validator object for this CategoryEntity</param>
		public CategoryEntity(System.String categoryid, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Categoryid = categoryid;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CategoryEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InventoryItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInventoryItems() { return CreateRelationInfoForNavigator("InventoryItems"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CategoryEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CategoryRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InventoryItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInventoryItems { get { return _staticMetaData.GetPrefetchPathElement("InventoryItems", CommonEntityBase.CreateEntityCollection<InventoryItemEntity>()); } }

		/// <summary>The Categoryid property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Category"."Categoryid".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Categoryid
		{
			get { return (System.String)GetValue((int)CategoryFieldIndex.Categoryid, true); }
			set { SetValue((int)CategoryFieldIndex.Categoryid, value); }
		}

		/// <summary>The Categoryname property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Category"."Categoryname".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Categoryname
		{
			get { return (System.String)GetValue((int)CategoryFieldIndex.Categoryname, true); }
			set { SetValue((int)CategoryFieldIndex.Categoryname, value); }
		}

		/// <summary>The Taxrateid property of the Entity Category<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Category"."Taxrateid".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Taxrateid
		{
			get { return (Nullable<System.Int16>)GetValue((int)CategoryFieldIndex.Taxrateid, false); }
			set { SetValue((int)CategoryFieldIndex.Taxrateid, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'InventoryItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InventoryItemEntity))]
		public virtual EntityCollection<InventoryItemEntity> InventoryItems { get { return GetOrCreateEntityCollection<InventoryItemEntity, InventoryItemEntityFactory>("Category", true, false, ref _inventoryItems); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CategoryFieldIndex
	{
		///<summary>Categoryid. </summary>
		Categoryid,
		///<summary>Categoryname. </summary>
		Categoryname,
		///<summary>Taxrateid. </summary>
		Taxrateid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Category. </summary>
	public partial class CategoryRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CategoryEntity and InventoryItemEntity over the 1:n relation they have, using the relation between the fields: Category.Categoryid - InventoryItem.Categoryid</summary>
		public virtual IEntityRelation InventoryItemEntityUsingCategoryid
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "InventoryItems", true, new[] { CategoryFields.Categoryid, InventoryItemFields.Categoryid }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCategoryRelations
	{
		internal static readonly IEntityRelation InventoryItemEntityUsingCategoryidStatic = new CategoryRelations().InventoryItemEntityUsingCategoryid;

		/// <summary>CTor</summary>
		static StaticCategoryRelations() { }
	}
}
