//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CostLedger'.<br/><br/></summary>
	[Serializable]
	public partial class CostLedgerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CostElementEntity _costElement;
		private CostObjectEntity _costObject;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CostLedgerEntityStaticMetaData _staticMetaData = new CostLedgerEntityStaticMetaData();
		private static CostLedgerRelations _relationsFactory = new CostLedgerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CostElement</summary>
			public static readonly string CostElement = "CostElement";
			/// <summary>Member name CostObject</summary>
			public static readonly string CostObject = "CostObject";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CostLedgerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CostLedgerEntityStaticMetaData()
			{
				SetEntityCoreInfo("CostLedgerEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CostLedgerEntity, typeof(CostLedgerEntity), typeof(CostLedgerEntityFactory), false);
				AddNavigatorMetaData<CostLedgerEntity, CostElementEntity>("CostElement", "CostLedgers", (a, b) => a._costElement = b, a => a._costElement, (a, b) => a.CostElement = b, DataAccess.RelationClasses.StaticCostLedgerRelations.CostElementEntityUsingExpenseAtributeIdStatic, ()=>new CostLedgerRelations().CostElementEntityUsingExpenseAtributeId, null, new int[] { (int)CostLedgerFieldIndex.ExpenseAtributeId }, null, true, (int)DataAccess.EntityType.CostElementEntity);
				AddNavigatorMetaData<CostLedgerEntity, CostObjectEntity>("CostObject", "CostLedgers", (a, b) => a._costObject = b, a => a._costObject, (a, b) => a.CostObject = b, DataAccess.RelationClasses.StaticCostLedgerRelations.CostObjectEntityUsingExobjectIdStatic, ()=>new CostLedgerRelations().CostObjectEntityUsingExobjectId, null, new int[] { (int)CostLedgerFieldIndex.ExobjectId }, null, true, (int)DataAccess.EntityType.CostObjectEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CostLedgerEntity()
		{
		}

		/// <summary> CTor</summary>
		public CostLedgerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CostLedgerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CostLedgerEntity</param>
		public CostLedgerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CostLedger which data should be fetched into this CostLedger object</param>
		public CostLedgerEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CostLedger which data should be fetched into this CostLedger object</param>
		/// <param name="validator">The custom validator object for this CostLedgerEntity</param>
		public CostLedgerEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CostLedgerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CostElement' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCostElement() { return CreateRelationInfoForNavigator("CostElement"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CostObject' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCostObject() { return CreateRelationInfoForNavigator("CostObject"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CostLedgerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CostLedgerRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CostElement' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCostElement { get { return _staticMetaData.GetPrefetchPathElement("CostElement", CommonEntityBase.CreateEntityCollection<CostElementEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CostObject' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCostObject { get { return _staticMetaData.GetPrefetchPathElement("CostObject", CommonEntityBase.CreateEntityCollection<CostObjectEntity>()); } }

		/// <summary>The Contents property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."Contents".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Contents
		{
			get { return (System.String)GetValue((int)CostLedgerFieldIndex.Contents, true); }
			set { SetValue((int)CostLedgerFieldIndex.Contents, value); }
		}

		/// <summary>The Credit property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."Credit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Credit
		{
			get { return (Nullable<System.Double>)GetValue((int)CostLedgerFieldIndex.Credit, false); }
			set { SetValue((int)CostLedgerFieldIndex.Credit, value); }
		}

		/// <summary>The Debit property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."Debit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Debit
		{
			get { return (Nullable<System.Double>)GetValue((int)CostLedgerFieldIndex.Debit, false); }
			set { SetValue((int)CostLedgerFieldIndex.Debit, value); }
		}

		/// <summary>The Endbalance property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."Endbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)CostLedgerFieldIndex.Endbalance, false); }
			set { SetValue((int)CostLedgerFieldIndex.Endbalance, value); }
		}

		/// <summary>The ExobjectId property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."ExobjectId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ExobjectId
		{
			get { return (System.String)GetValue((int)CostLedgerFieldIndex.ExobjectId, true); }
			set { SetValue((int)CostLedgerFieldIndex.ExobjectId, value); }
		}

		/// <summary>The ExpenseAtributeId property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."ExpenseAtributeId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ExpenseAtributeId
		{
			get { return (System.String)GetValue((int)CostLedgerFieldIndex.ExpenseAtributeId, true); }
			set { SetValue((int)CostLedgerFieldIndex.ExpenseAtributeId, value); }
		}

		/// <summary>The Id property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CostLedgerFieldIndex.Id, true); }
			set { SetValue((int)CostLedgerFieldIndex.Id, value); }
		}

		/// <summary>The JournalVoucherId property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."JournalVoucherId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> JournalVoucherId
		{
			get { return (Nullable<System.Int32>)GetValue((int)CostLedgerFieldIndex.JournalVoucherId, false); }
			set { SetValue((int)CostLedgerFieldIndex.JournalVoucherId, value); }
		}

		/// <summary>The VoucherDate property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."VoucherDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> VoucherDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CostLedgerFieldIndex.VoucherDate, false); }
			set { SetValue((int)CostLedgerFieldIndex.VoucherDate, value); }
		}

		/// <summary>The VoucherNo property of the Entity CostLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CostLedger"."VoucherNo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VoucherNo
		{
			get { return (System.String)GetValue((int)CostLedgerFieldIndex.VoucherNo, true); }
			set { SetValue((int)CostLedgerFieldIndex.VoucherNo, value); }
		}

		/// <summary>Gets / sets related entity of type 'CostElementEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CostElementEntity CostElement
		{
			get { return _costElement; }
			set { SetSingleRelatedEntityNavigator(value, "CostElement"); }
		}

		/// <summary>Gets / sets related entity of type 'CostObjectEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CostObjectEntity CostObject
		{
			get { return _costObject; }
			set { SetSingleRelatedEntityNavigator(value, "CostObject"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CostLedgerFieldIndex
	{
		///<summary>Contents. </summary>
		Contents,
		///<summary>Credit. </summary>
		Credit,
		///<summary>Debit. </summary>
		Debit,
		///<summary>Endbalance. </summary>
		Endbalance,
		///<summary>ExobjectId. </summary>
		ExobjectId,
		///<summary>ExpenseAtributeId. </summary>
		ExpenseAtributeId,
		///<summary>Id. </summary>
		Id,
		///<summary>JournalVoucherId. </summary>
		JournalVoucherId,
		///<summary>VoucherDate. </summary>
		VoucherDate,
		///<summary>VoucherNo. </summary>
		VoucherNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CostLedger. </summary>
	public partial class CostLedgerRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between CostLedgerEntity and CostElementEntity over the m:1 relation they have, using the relation between the fields: CostLedger.ExpenseAtributeId - CostElement.Id</summary>
		public virtual IEntityRelation CostElementEntityUsingExpenseAtributeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CostElement", false, new[] { CostElementFields.Id, CostLedgerFields.ExpenseAtributeId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CostLedgerEntity and CostObjectEntity over the m:1 relation they have, using the relation between the fields: CostLedger.ExobjectId - CostObject.Id</summary>
		public virtual IEntityRelation CostObjectEntityUsingExobjectId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CostObject", false, new[] { CostObjectFields.Id, CostLedgerFields.ExobjectId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCostLedgerRelations
	{
		internal static readonly IEntityRelation CostElementEntityUsingExpenseAtributeIdStatic = new CostLedgerRelations().CostElementEntityUsingExpenseAtributeId;
		internal static readonly IEntityRelation CostObjectEntityUsingExobjectIdStatic = new CostLedgerRelations().CostObjectEntityUsingExobjectId;

		/// <summary>CTor</summary>
		static StaticCostLedgerRelations() { }
	}
}
