//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CustomCostReportAccount'.<br/><br/></summary>
	[Serializable]
	public partial class CustomCostReportAccountEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CustomCostReportEntity _customCostReport;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CustomCostReportAccountEntityStaticMetaData _staticMetaData = new CustomCostReportAccountEntityStaticMetaData();
		private static CustomCostReportAccountRelations _relationsFactory = new CustomCostReportAccountRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CustomCostReport</summary>
			public static readonly string CustomCostReport = "CustomCostReport";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CustomCostReportAccountEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CustomCostReportAccountEntityStaticMetaData()
			{
				SetEntityCoreInfo("CustomCostReportAccountEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CustomCostReportAccountEntity, typeof(CustomCostReportAccountEntity), typeof(CustomCostReportAccountEntityFactory), false);
				AddNavigatorMetaData<CustomCostReportAccountEntity, CustomCostReportEntity>("CustomCostReport", "CustomCostReportAccounts", (a, b) => a._customCostReport = b, a => a._customCostReport, (a, b) => a.CustomCostReport = b, DataAccess.RelationClasses.StaticCustomCostReportAccountRelations.CustomCostReportEntityUsingCustomCostReportIdStatic, ()=>new CustomCostReportAccountRelations().CustomCostReportEntityUsingCustomCostReportId, null, new int[] { (int)CustomCostReportAccountFieldIndex.CustomCostReportId }, null, true, (int)DataAccess.EntityType.CustomCostReportEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CustomCostReportAccountEntity()
		{
		}

		/// <summary> CTor</summary>
		public CustomCostReportAccountEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CustomCostReportAccountEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CustomCostReportAccountEntity</param>
		public CustomCostReportAccountEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomCostReportAccount which data should be fetched into this CustomCostReportAccount object</param>
		public CustomCostReportAccountEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomCostReportAccount which data should be fetched into this CustomCostReportAccount object</param>
		/// <param name="validator">The custom validator object for this CustomCostReportAccountEntity</param>
		public CustomCostReportAccountEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CustomCostReportAccountEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CustomCostReport' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomCostReport() { return CreateRelationInfoForNavigator("CustomCostReport"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CustomCostReportAccountEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CustomCostReportAccountRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CustomCostReport' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomCostReport { get { return _staticMetaData.GetPrefetchPathElement("CustomCostReport", CommonEntityBase.CreateEntityCollection<CustomCostReportEntity>()); } }

		/// <summary>The AccountId property of the Entity CustomCostReportAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReportAccount"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AccountId
		{
			get { return (System.String)GetValue((int)CustomCostReportAccountFieldIndex.AccountId, true); }
			set { SetValue((int)CustomCostReportAccountFieldIndex.AccountId, value); }
		}

		/// <summary>The CustomCostReportId property of the Entity CustomCostReportAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReportAccount"."CustomCostReportId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> CustomCostReportId
		{
			get { return (Nullable<System.Int32>)GetValue((int)CustomCostReportAccountFieldIndex.CustomCostReportId, false); }
			set { SetValue((int)CustomCostReportAccountFieldIndex.CustomCostReportId, value); }
		}

		/// <summary>The Id property of the Entity CustomCostReportAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReportAccount"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CustomCostReportAccountFieldIndex.Id, true); }
			set { SetValue((int)CustomCostReportAccountFieldIndex.Id, value); }
		}

		/// <summary>Gets / sets related entity of type 'CustomCostReportEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CustomCostReportEntity CustomCostReport
		{
			get { return _customCostReport; }
			set { SetSingleRelatedEntityNavigator(value, "CustomCostReport"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CustomCostReportAccountFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>CustomCostReportId. </summary>
		CustomCostReportId,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CustomCostReportAccount. </summary>
	public partial class CustomCostReportAccountRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between CustomCostReportAccountEntity and CustomCostReportEntity over the m:1 relation they have, using the relation between the fields: CustomCostReportAccount.CustomCostReportId - CustomCostReport.Id</summary>
		public virtual IEntityRelation CustomCostReportEntityUsingCustomCostReportId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "CustomCostReport", false, new[] { CustomCostReportFields.Id, CustomCostReportAccountFields.CustomCostReportId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCustomCostReportAccountRelations
	{
		internal static readonly IEntityRelation CustomCostReportEntityUsingCustomCostReportIdStatic = new CustomCostReportAccountRelations().CustomCostReportEntityUsingCustomCostReportId;

		/// <summary>CTor</summary>
		static StaticCustomCostReportAccountRelations() { }
	}
}
