//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CustomCostReport'.<br/><br/></summary>
	[Serializable]
	public partial class CustomCostReportEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<CustomCostReportAccountEntity> _customCostReportAccounts;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CustomCostReportEntityStaticMetaData _staticMetaData = new CustomCostReportEntityStaticMetaData();
		private static CustomCostReportRelations _relationsFactory = new CustomCostReportRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CustomCostReportAccounts</summary>
			public static readonly string CustomCostReportAccounts = "CustomCostReportAccounts";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CustomCostReportEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CustomCostReportEntityStaticMetaData()
			{
				SetEntityCoreInfo("CustomCostReportEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.CustomCostReportEntity, typeof(CustomCostReportEntity), typeof(CustomCostReportEntityFactory), false);
				AddNavigatorMetaData<CustomCostReportEntity, EntityCollection<CustomCostReportAccountEntity>>("CustomCostReportAccounts", a => a._customCostReportAccounts, (a, b) => a._customCostReportAccounts = b, a => a.CustomCostReportAccounts, () => new CustomCostReportRelations().CustomCostReportAccountEntityUsingCustomCostReportId, typeof(CustomCostReportAccountEntity), (int)DataAccess.EntityType.CustomCostReportAccountEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CustomCostReportEntity()
		{
		}

		/// <summary> CTor</summary>
		public CustomCostReportEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CustomCostReportEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CustomCostReportEntity</param>
		public CustomCostReportEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomCostReport which data should be fetched into this CustomCostReport object</param>
		public CustomCostReportEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for CustomCostReport which data should be fetched into this CustomCostReport object</param>
		/// <param name="validator">The custom validator object for this CustomCostReportEntity</param>
		public CustomCostReportEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CustomCostReportEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CustomCostReportAccount' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomCostReportAccounts() { return CreateRelationInfoForNavigator("CustomCostReportAccounts"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CustomCostReportEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CustomCostReportRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CustomCostReportAccount' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomCostReportAccounts { get { return _staticMetaData.GetPrefetchPathElement("CustomCostReportAccounts", CommonEntityBase.CreateEntityCollection<CustomCostReportAccountEntity>()); } }

		/// <summary>The BookName property of the Entity CustomCostReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReport"."BookName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String BookName
		{
			get { return (System.String)GetValue((int)CustomCostReportFieldIndex.BookName, true); }
			set { SetValue((int)CustomCostReportFieldIndex.BookName, value); }
		}

		/// <summary>The BookType property of the Entity CustomCostReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReport"."BookType".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> BookType
		{
			get { return (Nullable<System.Int16>)GetValue((int)CustomCostReportFieldIndex.BookType, false); }
			set { SetValue((int)CustomCostReportFieldIndex.BookType, value); }
		}

		/// <summary>The Dbcr property of the Entity CustomCostReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReport"."Dbcr".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Dbcr
		{
			get { return (Nullable<System.Int16>)GetValue((int)CustomCostReportFieldIndex.Dbcr, false); }
			set { SetValue((int)CustomCostReportFieldIndex.Dbcr, value); }
		}

		/// <summary>The Id property of the Entity CustomCostReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "CustomCostReport"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)CustomCostReportFieldIndex.Id, true); }
			set { SetValue((int)CustomCostReportFieldIndex.Id, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CustomCostReportAccountEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CustomCostReportAccountEntity))]
		public virtual EntityCollection<CustomCostReportAccountEntity> CustomCostReportAccounts { get { return GetOrCreateEntityCollection<CustomCostReportAccountEntity, CustomCostReportAccountEntityFactory>("CustomCostReport", true, false, ref _customCostReportAccounts); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum CustomCostReportFieldIndex
	{
		///<summary>BookName. </summary>
		BookName,
		///<summary>BookType. </summary>
		BookType,
		///<summary>Dbcr. </summary>
		Dbcr,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CustomCostReport. </summary>
	public partial class CustomCostReportRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CustomCostReportEntity and CustomCostReportAccountEntity over the 1:n relation they have, using the relation between the fields: CustomCostReport.Id - CustomCostReportAccount.CustomCostReportId</summary>
		public virtual IEntityRelation CustomCostReportAccountEntityUsingCustomCostReportId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CustomCostReportAccounts", true, new[] { CustomCostReportFields.Id, CustomCostReportAccountFields.CustomCostReportId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCustomCostReportRelations
	{
		internal static readonly IEntityRelation CustomCostReportAccountEntityUsingCustomCostReportIdStatic = new CustomCostReportRelations().CustomCostReportAccountEntityUsingCustomCostReportId;

		/// <summary>CTor</summary>
		static StaticCustomCostReportRelations() { }
	}
}
