//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'DebtDetail'.<br/><br/></summary>
	[Serializable]
	public partial class DebtDetailEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private DebtReasonEntity _debtReason;
		private DebtTypeEntity _debtType;
		private JournalEntryEntity _journalEntry;
		private LiabilityDueEntity _liabilityDue;
		private PartnerEntity _partner;
		private CurrencyLiabilityLineEntity _currencyLiabilityLine;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DebtDetailEntityStaticMetaData _staticMetaData = new DebtDetailEntityStaticMetaData();
		private static DebtDetailRelations _relationsFactory = new DebtDetailRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name DebtReason</summary>
			public static readonly string DebtReason = "DebtReason";
			/// <summary>Member name DebtType</summary>
			public static readonly string DebtType = "DebtType";
			/// <summary>Member name JournalEntry</summary>
			public static readonly string JournalEntry = "JournalEntry";
			/// <summary>Member name LiabilityDue</summary>
			public static readonly string LiabilityDue = "LiabilityDue";
			/// <summary>Member name Partner</summary>
			public static readonly string Partner = "Partner";
			/// <summary>Member name CurrencyLiabilityLine</summary>
			public static readonly string CurrencyLiabilityLine = "CurrencyLiabilityLine";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DebtDetailEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DebtDetailEntityStaticMetaData()
			{
				SetEntityCoreInfo("DebtDetailEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.DebtDetailEntity, typeof(DebtDetailEntity), typeof(DebtDetailEntityFactory), false);
				AddNavigatorMetaData<DebtDetailEntity, DebtReasonEntity>("DebtReason", "DebtDetails", (a, b) => a._debtReason = b, a => a._debtReason, (a, b) => a.DebtReason = b, DataAccess.RelationClasses.StaticDebtDetailRelations.DebtReasonEntityUsingDebtReasonIdStatic, ()=>new DebtDetailRelations().DebtReasonEntityUsingDebtReasonId, null, new int[] { (int)DebtDetailFieldIndex.DebtReasonId }, null, true, (int)DataAccess.EntityType.DebtReasonEntity);
				AddNavigatorMetaData<DebtDetailEntity, DebtTypeEntity>("DebtType", "DebtDetails", (a, b) => a._debtType = b, a => a._debtType, (a, b) => a.DebtType = b, DataAccess.RelationClasses.StaticDebtDetailRelations.DebtTypeEntityUsingDebtTypeIdStatic, ()=>new DebtDetailRelations().DebtTypeEntityUsingDebtTypeId, null, new int[] { (int)DebtDetailFieldIndex.DebtTypeId }, null, true, (int)DataAccess.EntityType.DebtTypeEntity);
				AddNavigatorMetaData<DebtDetailEntity, JournalEntryEntity>("JournalEntry", "DebtDetails", (a, b) => a._journalEntry = b, a => a._journalEntry, (a, b) => a.JournalEntry = b, DataAccess.RelationClasses.StaticDebtDetailRelations.JournalEntryEntityUsingJournalEntryIdStatic, ()=>new DebtDetailRelations().JournalEntryEntityUsingJournalEntryId, null, new int[] { (int)DebtDetailFieldIndex.JournalEntryId }, null, true, (int)DataAccess.EntityType.JournalEntryEntity);
				AddNavigatorMetaData<DebtDetailEntity, LiabilityDueEntity>("LiabilityDue", "DebtDetails", (a, b) => a._liabilityDue = b, a => a._liabilityDue, (a, b) => a.LiabilityDue = b, DataAccess.RelationClasses.StaticDebtDetailRelations.LiabilityDueEntityUsingLiabilityDuesIdStatic, ()=>new DebtDetailRelations().LiabilityDueEntityUsingLiabilityDuesId, null, new int[] { (int)DebtDetailFieldIndex.LiabilityDuesId }, null, true, (int)DataAccess.EntityType.LiabilityDueEntity);
				AddNavigatorMetaData<DebtDetailEntity, PartnerEntity>("Partner", "DebtDetails", (a, b) => a._partner = b, a => a._partner, (a, b) => a.Partner = b, DataAccess.RelationClasses.StaticDebtDetailRelations.PartnerEntityUsingPartnerIdStatic, ()=>new DebtDetailRelations().PartnerEntityUsingPartnerId, null, new int[] { (int)DebtDetailFieldIndex.PartnerId }, null, true, (int)DataAccess.EntityType.PartnerEntity);
				AddNavigatorMetaData<DebtDetailEntity, CurrencyLiabilityLineEntity>("CurrencyLiabilityLine", "DebtDetail", (a, b) => a._currencyLiabilityLine = b, a => a._currencyLiabilityLine, (a, b) => a.CurrencyLiabilityLine = b, DataAccess.RelationClasses.StaticDebtDetailRelations.CurrencyLiabilityLineEntityUsingLineIdStatic, ()=>new DebtDetailRelations().CurrencyLiabilityLineEntityUsingLineId, null, null, null, true, (int)DataAccess.EntityType.CurrencyLiabilityLineEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DebtDetailEntity()
		{
		}

		/// <summary> CTor</summary>
		public DebtDetailEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DebtDetailEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DebtDetailEntity</param>
		public DebtDetailEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtDetail which data should be fetched into this DebtDetail object</param>
		public DebtDetailEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtDetail which data should be fetched into this DebtDetail object</param>
		/// <param name="validator">The custom validator object for this DebtDetailEntity</param>
		public DebtDetailEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DebtDetailEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'DebtReason' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtReason() { return CreateRelationInfoForNavigator("DebtReason"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'DebtType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtType() { return CreateRelationInfoForNavigator("DebtType"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'JournalEntry' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoJournalEntry() { return CreateRelationInfoForNavigator("JournalEntry"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'LiabilityDue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLiabilityDue() { return CreateRelationInfoForNavigator("LiabilityDue"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Partner' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPartner() { return CreateRelationInfoForNavigator("Partner"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'CurrencyLiabilityLine' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCurrencyLiabilityLine() { return CreateRelationInfoForNavigator("CurrencyLiabilityLine"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DebtDetailEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DebtDetailRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtReason' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtReason { get { return _staticMetaData.GetPrefetchPathElement("DebtReason", CommonEntityBase.CreateEntityCollection<DebtReasonEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtType { get { return _staticMetaData.GetPrefetchPathElement("DebtType", CommonEntityBase.CreateEntityCollection<DebtTypeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'JournalEntry' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathJournalEntry { get { return _staticMetaData.GetPrefetchPathElement("JournalEntry", CommonEntityBase.CreateEntityCollection<JournalEntryEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LiabilityDue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLiabilityDue { get { return _staticMetaData.GetPrefetchPathElement("LiabilityDue", CommonEntityBase.CreateEntityCollection<LiabilityDueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Partner' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPartner { get { return _staticMetaData.GetPrefetchPathElement("Partner", CommonEntityBase.CreateEntityCollection<PartnerEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CurrencyLiabilityLine' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCurrencyLiabilityLine { get { return _staticMetaData.GetPrefetchPathElement("CurrencyLiabilityLine", CommonEntityBase.CreateEntityCollection<CurrencyLiabilityLineEntity>()); } }

		/// <summary>The Amount property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."Amount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Amount
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtDetailFieldIndex.Amount, false); }
			set { SetValue((int)DebtDetailFieldIndex.Amount, value); }
		}

		/// <summary>The Currency property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."Currency".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Currency
		{
			get { return (System.Boolean)GetValue((int)DebtDetailFieldIndex.Currency, true); }
			set { SetValue((int)DebtDetailFieldIndex.Currency, value); }
		}

		/// <summary>The DebtReasonId property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."DebtReasonId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> DebtReasonId
		{
			get { return (Nullable<System.Int32>)GetValue((int)DebtDetailFieldIndex.DebtReasonId, false); }
			set { SetValue((int)DebtDetailFieldIndex.DebtReasonId, value); }
		}

		/// <summary>The DebtTypeId property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."DebtTypeId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DebtTypeId
		{
			get { return (System.String)GetValue((int)DebtDetailFieldIndex.DebtTypeId, true); }
			set { SetValue((int)DebtDetailFieldIndex.DebtTypeId, value); }
		}

		/// <summary>The Id property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DebtDetailFieldIndex.Id, true); }
			set { SetValue((int)DebtDetailFieldIndex.Id, value); }
		}

		/// <summary>The Interestflag property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."Interestflag".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Interestflag
		{
			get { return (System.Boolean)GetValue((int)DebtDetailFieldIndex.Interestflag, true); }
			set { SetValue((int)DebtDetailFieldIndex.Interestflag, value); }
		}

		/// <summary>The JournalEntryId property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."JournalEntryId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> JournalEntryId
		{
			get { return (Nullable<System.Int32>)GetValue((int)DebtDetailFieldIndex.JournalEntryId, false); }
			set { SetValue((int)DebtDetailFieldIndex.JournalEntryId, value); }
		}

		/// <summary>The Liabilitydate property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."Liabilitydate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Liabilitydate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)DebtDetailFieldIndex.Liabilitydate, false); }
			set { SetValue((int)DebtDetailFieldIndex.Liabilitydate, value); }
		}

		/// <summary>The LiabilityDuesId property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."LiabilityDuesId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LiabilityDuesId
		{
			get { return (Nullable<System.Int32>)GetValue((int)DebtDetailFieldIndex.LiabilityDuesId, false); }
			set { SetValue((int)DebtDetailFieldIndex.LiabilityDuesId, value); }
		}

		/// <summary>The PartnerId property of the Entity DebtDetail<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtDetail"."PartnerId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PartnerId
		{
			get { return (System.String)GetValue((int)DebtDetailFieldIndex.PartnerId, true); }
			set { SetValue((int)DebtDetailFieldIndex.PartnerId, value); }
		}

		/// <summary>Gets / sets related entity of type 'DebtReasonEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DebtReasonEntity DebtReason
		{
			get { return _debtReason; }
			set { SetSingleRelatedEntityNavigator(value, "DebtReason"); }
		}

		/// <summary>Gets / sets related entity of type 'DebtTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DebtTypeEntity DebtType
		{
			get { return _debtType; }
			set { SetSingleRelatedEntityNavigator(value, "DebtType"); }
		}

		/// <summary>Gets / sets related entity of type 'JournalEntryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual JournalEntryEntity JournalEntry
		{
			get { return _journalEntry; }
			set { SetSingleRelatedEntityNavigator(value, "JournalEntry"); }
		}

		/// <summary>Gets / sets related entity of type 'LiabilityDueEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual LiabilityDueEntity LiabilityDue
		{
			get { return _liabilityDue; }
			set { SetSingleRelatedEntityNavigator(value, "LiabilityDue"); }
		}

		/// <summary>Gets / sets related entity of type 'PartnerEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PartnerEntity Partner
		{
			get { return _partner; }
			set { SetSingleRelatedEntityNavigator(value, "Partner"); }
		}

		/// <summary>Gets / sets related entity of type 'CurrencyLiabilityLineEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned.<br/><br/></summary>
		[Browsable(false)]
		public virtual CurrencyLiabilityLineEntity CurrencyLiabilityLine
		{
			get { return _currencyLiabilityLine; }
			set { SetSingleRelatedEntityNavigator(value, "CurrencyLiabilityLine"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum DebtDetailFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>Currency. </summary>
		Currency,
		///<summary>DebtReasonId. </summary>
		DebtReasonId,
		///<summary>DebtTypeId. </summary>
		DebtTypeId,
		///<summary>Id. </summary>
		Id,
		///<summary>Interestflag. </summary>
		Interestflag,
		///<summary>JournalEntryId. </summary>
		JournalEntryId,
		///<summary>Liabilitydate. </summary>
		Liabilitydate,
		///<summary>LiabilityDuesId. </summary>
		LiabilityDuesId,
		///<summary>PartnerId. </summary>
		PartnerId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: DebtDetail. </summary>
	public partial class DebtDetailRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and CurrencyLiabilityLineEntity over the 1:1 relation they have, using the relation between the fields: DebtDetail.Id - CurrencyLiabilityLine.LineId</summary>
		public virtual IEntityRelation CurrencyLiabilityLineEntityUsingLineId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToOne, "CurrencyLiabilityLine", true, new[] { DebtDetailFields.Id, CurrencyLiabilityLineFields.LineId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and DebtReasonEntity over the m:1 relation they have, using the relation between the fields: DebtDetail.DebtReasonId - DebtReason.Id</summary>
		public virtual IEntityRelation DebtReasonEntityUsingDebtReasonId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "DebtReason", false, new[] { DebtReasonFields.Id, DebtDetailFields.DebtReasonId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and DebtTypeEntity over the m:1 relation they have, using the relation between the fields: DebtDetail.DebtTypeId - DebtType.Id</summary>
		public virtual IEntityRelation DebtTypeEntityUsingDebtTypeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "DebtType", false, new[] { DebtTypeFields.Id, DebtDetailFields.DebtTypeId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and JournalEntryEntity over the m:1 relation they have, using the relation between the fields: DebtDetail.JournalEntryId - JournalEntry.Id</summary>
		public virtual IEntityRelation JournalEntryEntityUsingJournalEntryId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "JournalEntry", false, new[] { JournalEntryFields.Id, DebtDetailFields.JournalEntryId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and LiabilityDueEntity over the m:1 relation they have, using the relation between the fields: DebtDetail.LiabilityDuesId - LiabilityDue.Id</summary>
		public virtual IEntityRelation LiabilityDueEntityUsingLiabilityDuesId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "LiabilityDue", false, new[] { LiabilityDueFields.Id, DebtDetailFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtDetailEntity and PartnerEntity over the m:1 relation they have, using the relation between the fields: DebtDetail.PartnerId - Partner.Id</summary>
		public virtual IEntityRelation PartnerEntityUsingPartnerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Partner", false, new[] { PartnerFields.Id, DebtDetailFields.PartnerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDebtDetailRelations
	{
		internal static readonly IEntityRelation CurrencyLiabilityLineEntityUsingLineIdStatic = new DebtDetailRelations().CurrencyLiabilityLineEntityUsingLineId;
		internal static readonly IEntityRelation DebtReasonEntityUsingDebtReasonIdStatic = new DebtDetailRelations().DebtReasonEntityUsingDebtReasonId;
		internal static readonly IEntityRelation DebtTypeEntityUsingDebtTypeIdStatic = new DebtDetailRelations().DebtTypeEntityUsingDebtTypeId;
		internal static readonly IEntityRelation JournalEntryEntityUsingJournalEntryIdStatic = new DebtDetailRelations().JournalEntryEntityUsingJournalEntryId;
		internal static readonly IEntityRelation LiabilityDueEntityUsingLiabilityDuesIdStatic = new DebtDetailRelations().LiabilityDueEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation PartnerEntityUsingPartnerIdStatic = new DebtDetailRelations().PartnerEntityUsingPartnerId;

		/// <summary>CTor</summary>
		static StaticDebtDetailRelations() { }
	}
}
