//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'DebtBalance'.<br/><br/></summary>
	[Serializable]
	public partial class DebtBalanceEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ChartOfAccountEntity _chartOfAccount;
		private DebtTypeEntity _debtType;
		private PartnerEntity _partner;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DebtBalanceEntityStaticMetaData _staticMetaData = new DebtBalanceEntityStaticMetaData();
		private static DebtBalanceRelations _relationsFactory = new DebtBalanceRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ChartOfAccount</summary>
			public static readonly string ChartOfAccount = "ChartOfAccount";
			/// <summary>Member name DebtType</summary>
			public static readonly string DebtType = "DebtType";
			/// <summary>Member name Partner</summary>
			public static readonly string Partner = "Partner";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DebtBalanceEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DebtBalanceEntityStaticMetaData()
			{
				SetEntityCoreInfo("DebtBalanceEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.DebtBalanceEntity, typeof(DebtBalanceEntity), typeof(DebtBalanceEntityFactory), false);
				AddNavigatorMetaData<DebtBalanceEntity, ChartOfAccountEntity>("ChartOfAccount", "DebtBalances", (a, b) => a._chartOfAccount = b, a => a._chartOfAccount, (a, b) => a.ChartOfAccount = b, DataAccess.RelationClasses.StaticDebtBalanceRelations.ChartOfAccountEntityUsingAccountIdStatic, ()=>new DebtBalanceRelations().ChartOfAccountEntityUsingAccountId, null, new int[] { (int)DebtBalanceFieldIndex.AccountId }, null, true, (int)DataAccess.EntityType.ChartOfAccountEntity);
				AddNavigatorMetaData<DebtBalanceEntity, DebtTypeEntity>("DebtType", "DebtBalances", (a, b) => a._debtType = b, a => a._debtType, (a, b) => a.DebtType = b, DataAccess.RelationClasses.StaticDebtBalanceRelations.DebtTypeEntityUsingDebtTypeIdStatic, ()=>new DebtBalanceRelations().DebtTypeEntityUsingDebtTypeId, null, new int[] { (int)DebtBalanceFieldIndex.DebtTypeId }, null, true, (int)DataAccess.EntityType.DebtTypeEntity);
				AddNavigatorMetaData<DebtBalanceEntity, PartnerEntity>("Partner", "DebtBalances", (a, b) => a._partner = b, a => a._partner, (a, b) => a.Partner = b, DataAccess.RelationClasses.StaticDebtBalanceRelations.PartnerEntityUsingPartnerIdStatic, ()=>new DebtBalanceRelations().PartnerEntityUsingPartnerId, null, new int[] { (int)DebtBalanceFieldIndex.PartnerId }, null, true, (int)DataAccess.EntityType.PartnerEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DebtBalanceEntity()
		{
		}

		/// <summary> CTor</summary>
		public DebtBalanceEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DebtBalanceEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DebtBalanceEntity</param>
		public DebtBalanceEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtBalance which data should be fetched into this DebtBalance object</param>
		public DebtBalanceEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtBalance which data should be fetched into this DebtBalance object</param>
		/// <param name="validator">The custom validator object for this DebtBalanceEntity</param>
		public DebtBalanceEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DebtBalanceEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ChartOfAccount' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoChartOfAccount() { return CreateRelationInfoForNavigator("ChartOfAccount"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'DebtType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtType() { return CreateRelationInfoForNavigator("DebtType"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Partner' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPartner() { return CreateRelationInfoForNavigator("Partner"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DebtBalanceEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DebtBalanceRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ChartOfAccount' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathChartOfAccount { get { return _staticMetaData.GetPrefetchPathElement("ChartOfAccount", CommonEntityBase.CreateEntityCollection<ChartOfAccountEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtType { get { return _staticMetaData.GetPrefetchPathElement("DebtType", CommonEntityBase.CreateEntityCollection<DebtTypeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Partner' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPartner { get { return _staticMetaData.GetPrefetchPathElement("Partner", CommonEntityBase.CreateEntityCollection<PartnerEntity>()); } }

		/// <summary>The AccountId property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AccountId
		{
			get { return (System.String)GetValue((int)DebtBalanceFieldIndex.AccountId, true); }
			set { SetValue((int)DebtBalanceFieldIndex.AccountId, value); }
		}

		/// <summary>The Beginbalance property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Beginbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Beginbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Beginbalance, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Beginbalance, value); }
		}

		/// <summary>The Begincredit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Begincredit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Begincredit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Begincredit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Begincredit, value); }
		}

		/// <summary>The Begindebit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Begindebit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Begindebit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Begindebit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Begindebit, value); }
		}

		/// <summary>The DebtTypeId property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."DebtTypeId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DebtTypeId
		{
			get { return (System.String)GetValue((int)DebtBalanceFieldIndex.DebtTypeId, true); }
			set { SetValue((int)DebtBalanceFieldIndex.DebtTypeId, value); }
		}

		/// <summary>The Endbalance property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Endbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Endbalance, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Endbalance, value); }
		}

		/// <summary>The Endcredit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Endcredit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endcredit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Endcredit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Endcredit, value); }
		}

		/// <summary>The Enddebit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Enddebit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Enddebit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Enddebit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Enddebit, value); }
		}

		/// <summary>The Id property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DebtBalanceFieldIndex.Id, true); }
			set { SetValue((int)DebtBalanceFieldIndex.Id, value); }
		}

		/// <summary>The Inbalance property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Inbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Inbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Inbalance, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Inbalance, value); }
		}

		/// <summary>The Incredit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Incredit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Incredit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Incredit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Incredit, value); }
		}

		/// <summary>The Indebit property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."Indebit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Indebit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtBalanceFieldIndex.Indebit, false); }
			set { SetValue((int)DebtBalanceFieldIndex.Indebit, value); }
		}

		/// <summary>The LongtermFlag property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."LongtermFlag".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> LongtermFlag
		{
			get { return (Nullable<System.Int16>)GetValue((int)DebtBalanceFieldIndex.LongtermFlag, false); }
			set { SetValue((int)DebtBalanceFieldIndex.LongtermFlag, value); }
		}

		/// <summary>The PartnerId property of the Entity DebtBalance<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtBalance"."PartnerId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String PartnerId
		{
			get { return (System.String)GetValue((int)DebtBalanceFieldIndex.PartnerId, true); }
			set { SetValue((int)DebtBalanceFieldIndex.PartnerId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ChartOfAccountEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ChartOfAccountEntity ChartOfAccount
		{
			get { return _chartOfAccount; }
			set { SetSingleRelatedEntityNavigator(value, "ChartOfAccount"); }
		}

		/// <summary>Gets / sets related entity of type 'DebtTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DebtTypeEntity DebtType
		{
			get { return _debtType; }
			set { SetSingleRelatedEntityNavigator(value, "DebtType"); }
		}

		/// <summary>Gets / sets related entity of type 'PartnerEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PartnerEntity Partner
		{
			get { return _partner; }
			set { SetSingleRelatedEntityNavigator(value, "Partner"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum DebtBalanceFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>Beginbalance. </summary>
		Beginbalance,
		///<summary>Begincredit. </summary>
		Begincredit,
		///<summary>Begindebit. </summary>
		Begindebit,
		///<summary>DebtTypeId. </summary>
		DebtTypeId,
		///<summary>Endbalance. </summary>
		Endbalance,
		///<summary>Endcredit. </summary>
		Endcredit,
		///<summary>Enddebit. </summary>
		Enddebit,
		///<summary>Id. </summary>
		Id,
		///<summary>Inbalance. </summary>
		Inbalance,
		///<summary>Incredit. </summary>
		Incredit,
		///<summary>Indebit. </summary>
		Indebit,
		///<summary>LongtermFlag. </summary>
		LongtermFlag,
		///<summary>PartnerId. </summary>
		PartnerId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: DebtBalance. </summary>
	public partial class DebtBalanceRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DebtBalanceEntity and ChartOfAccountEntity over the m:1 relation they have, using the relation between the fields: DebtBalance.AccountId - ChartOfAccount.AccountId</summary>
		public virtual IEntityRelation ChartOfAccountEntityUsingAccountId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ChartOfAccount", false, new[] { ChartOfAccountFields.AccountId, DebtBalanceFields.AccountId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtBalanceEntity and DebtTypeEntity over the m:1 relation they have, using the relation between the fields: DebtBalance.DebtTypeId - DebtType.Id</summary>
		public virtual IEntityRelation DebtTypeEntityUsingDebtTypeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "DebtType", false, new[] { DebtTypeFields.Id, DebtBalanceFields.DebtTypeId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtBalanceEntity and PartnerEntity over the m:1 relation they have, using the relation between the fields: DebtBalance.PartnerId - Partner.Id</summary>
		public virtual IEntityRelation PartnerEntityUsingPartnerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Partner", false, new[] { PartnerFields.Id, DebtBalanceFields.PartnerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDebtBalanceRelations
	{
		internal static readonly IEntityRelation ChartOfAccountEntityUsingAccountIdStatic = new DebtBalanceRelations().ChartOfAccountEntityUsingAccountId;
		internal static readonly IEntityRelation DebtTypeEntityUsingDebtTypeIdStatic = new DebtBalanceRelations().DebtTypeEntityUsingDebtTypeId;
		internal static readonly IEntityRelation PartnerEntityUsingPartnerIdStatic = new DebtBalanceRelations().PartnerEntityUsingPartnerId;

		/// <summary>CTor</summary>
		static StaticDebtBalanceRelations() { }
	}
}
