//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'DebtLedger'.<br/><br/></summary>
	[Serializable]
	public partial class DebtLedgerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private DebtTypeEntity _debtType;
		private LiabilityDueEntity _liabilityDue;
		private PartnerEntity _partner;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DebtLedgerEntityStaticMetaData _staticMetaData = new DebtLedgerEntityStaticMetaData();
		private static DebtLedgerRelations _relationsFactory = new DebtLedgerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name DebtType</summary>
			public static readonly string DebtType = "DebtType";
			/// <summary>Member name LiabilityDue</summary>
			public static readonly string LiabilityDue = "LiabilityDue";
			/// <summary>Member name Partner</summary>
			public static readonly string Partner = "Partner";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DebtLedgerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DebtLedgerEntityStaticMetaData()
			{
				SetEntityCoreInfo("DebtLedgerEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.DebtLedgerEntity, typeof(DebtLedgerEntity), typeof(DebtLedgerEntityFactory), false);
				AddNavigatorMetaData<DebtLedgerEntity, DebtTypeEntity>("DebtType", "DebtLedgers", (a, b) => a._debtType = b, a => a._debtType, (a, b) => a.DebtType = b, DataAccess.RelationClasses.StaticDebtLedgerRelations.DebtTypeEntityUsingDebtTypeIdStatic, ()=>new DebtLedgerRelations().DebtTypeEntityUsingDebtTypeId, null, new int[] { (int)DebtLedgerFieldIndex.DebtTypeId }, null, true, (int)DataAccess.EntityType.DebtTypeEntity);
				AddNavigatorMetaData<DebtLedgerEntity, LiabilityDueEntity>("LiabilityDue", "DebtLedgers", (a, b) => a._liabilityDue = b, a => a._liabilityDue, (a, b) => a.LiabilityDue = b, DataAccess.RelationClasses.StaticDebtLedgerRelations.LiabilityDueEntityUsingLiabilityDuesIdStatic, ()=>new DebtLedgerRelations().LiabilityDueEntityUsingLiabilityDuesId, null, new int[] { (int)DebtLedgerFieldIndex.LiabilityDuesId }, null, true, (int)DataAccess.EntityType.LiabilityDueEntity);
				AddNavigatorMetaData<DebtLedgerEntity, PartnerEntity>("Partner", "DebtLedgers", (a, b) => a._partner = b, a => a._partner, (a, b) => a.Partner = b, DataAccess.RelationClasses.StaticDebtLedgerRelations.PartnerEntityUsingCustomerIdStatic, ()=>new DebtLedgerRelations().PartnerEntityUsingCustomerId, null, new int[] { (int)DebtLedgerFieldIndex.CustomerId }, null, true, (int)DataAccess.EntityType.PartnerEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DebtLedgerEntity()
		{
		}

		/// <summary> CTor</summary>
		public DebtLedgerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DebtLedgerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DebtLedgerEntity</param>
		public DebtLedgerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtLedger which data should be fetched into this DebtLedger object</param>
		public DebtLedgerEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for DebtLedger which data should be fetched into this DebtLedger object</param>
		/// <param name="validator">The custom validator object for this DebtLedgerEntity</param>
		public DebtLedgerEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DebtLedgerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'DebtType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtType() { return CreateRelationInfoForNavigator("DebtType"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'LiabilityDue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLiabilityDue() { return CreateRelationInfoForNavigator("LiabilityDue"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Partner' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPartner() { return CreateRelationInfoForNavigator("Partner"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DebtLedgerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DebtLedgerRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtType { get { return _staticMetaData.GetPrefetchPathElement("DebtType", CommonEntityBase.CreateEntityCollection<DebtTypeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LiabilityDue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLiabilityDue { get { return _staticMetaData.GetPrefetchPathElement("LiabilityDue", CommonEntityBase.CreateEntityCollection<LiabilityDueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Partner' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPartner { get { return _staticMetaData.GetPrefetchPathElement("Partner", CommonEntityBase.CreateEntityCollection<PartnerEntity>()); } }

		/// <summary>The Contents property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."Contents".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Contents
		{
			get { return (System.String)GetValue((int)DebtLedgerFieldIndex.Contents, true); }
			set { SetValue((int)DebtLedgerFieldIndex.Contents, value); }
		}

		/// <summary>The Credit property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."Credit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Credit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtLedgerFieldIndex.Credit, false); }
			set { SetValue((int)DebtLedgerFieldIndex.Credit, value); }
		}

		/// <summary>The CustomerId property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."CustomerId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CustomerId
		{
			get { return (System.String)GetValue((int)DebtLedgerFieldIndex.CustomerId, true); }
			set { SetValue((int)DebtLedgerFieldIndex.CustomerId, value); }
		}

		/// <summary>The Debit property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."Debit".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Debit
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtLedgerFieldIndex.Debit, false); }
			set { SetValue((int)DebtLedgerFieldIndex.Debit, value); }
		}

		/// <summary>The DebtTypeId property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."DebtTypeId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DebtTypeId
		{
			get { return (System.String)GetValue((int)DebtLedgerFieldIndex.DebtTypeId, true); }
			set { SetValue((int)DebtLedgerFieldIndex.DebtTypeId, value); }
		}

		/// <summary>The Endbalance property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."Endbalance".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endbalance
		{
			get { return (Nullable<System.Double>)GetValue((int)DebtLedgerFieldIndex.Endbalance, false); }
			set { SetValue((int)DebtLedgerFieldIndex.Endbalance, value); }
		}

		/// <summary>The Id property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DebtLedgerFieldIndex.Id, true); }
			set { SetValue((int)DebtLedgerFieldIndex.Id, value); }
		}

		/// <summary>The JournalVoucherId property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."JournalVoucherId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> JournalVoucherId
		{
			get { return (Nullable<System.Int32>)GetValue((int)DebtLedgerFieldIndex.JournalVoucherId, false); }
			set { SetValue((int)DebtLedgerFieldIndex.JournalVoucherId, value); }
		}

		/// <summary>The LiabilityDuesId property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."LiabilityDuesId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> LiabilityDuesId
		{
			get { return (Nullable<System.Int32>)GetValue((int)DebtLedgerFieldIndex.LiabilityDuesId, false); }
			set { SetValue((int)DebtLedgerFieldIndex.LiabilityDuesId, value); }
		}

		/// <summary>The VoucherDate property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."VoucherDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> VoucherDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)DebtLedgerFieldIndex.VoucherDate, false); }
			set { SetValue((int)DebtLedgerFieldIndex.VoucherDate, value); }
		}

		/// <summary>The VoucherNo property of the Entity DebtLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "DebtLedger"."VoucherNo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VoucherNo
		{
			get { return (System.String)GetValue((int)DebtLedgerFieldIndex.VoucherNo, true); }
			set { SetValue((int)DebtLedgerFieldIndex.VoucherNo, value); }
		}

		/// <summary>Gets / sets related entity of type 'DebtTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DebtTypeEntity DebtType
		{
			get { return _debtType; }
			set { SetSingleRelatedEntityNavigator(value, "DebtType"); }
		}

		/// <summary>Gets / sets related entity of type 'LiabilityDueEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual LiabilityDueEntity LiabilityDue
		{
			get { return _liabilityDue; }
			set { SetSingleRelatedEntityNavigator(value, "LiabilityDue"); }
		}

		/// <summary>Gets / sets related entity of type 'PartnerEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PartnerEntity Partner
		{
			get { return _partner; }
			set { SetSingleRelatedEntityNavigator(value, "Partner"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum DebtLedgerFieldIndex
	{
		///<summary>Contents. </summary>
		Contents,
		///<summary>Credit. </summary>
		Credit,
		///<summary>CustomerId. </summary>
		CustomerId,
		///<summary>Debit. </summary>
		Debit,
		///<summary>DebtTypeId. </summary>
		DebtTypeId,
		///<summary>Endbalance. </summary>
		Endbalance,
		///<summary>Id. </summary>
		Id,
		///<summary>JournalVoucherId. </summary>
		JournalVoucherId,
		///<summary>LiabilityDuesId. </summary>
		LiabilityDuesId,
		///<summary>VoucherDate. </summary>
		VoucherDate,
		///<summary>VoucherNo. </summary>
		VoucherNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: DebtLedger. </summary>
	public partial class DebtLedgerRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DebtLedgerEntity and DebtTypeEntity over the m:1 relation they have, using the relation between the fields: DebtLedger.DebtTypeId - DebtType.Id</summary>
		public virtual IEntityRelation DebtTypeEntityUsingDebtTypeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "DebtType", false, new[] { DebtTypeFields.Id, DebtLedgerFields.DebtTypeId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtLedgerEntity and LiabilityDueEntity over the m:1 relation they have, using the relation between the fields: DebtLedger.LiabilityDuesId - LiabilityDue.Id</summary>
		public virtual IEntityRelation LiabilityDueEntityUsingLiabilityDuesId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "LiabilityDue", false, new[] { LiabilityDueFields.Id, DebtLedgerFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DebtLedgerEntity and PartnerEntity over the m:1 relation they have, using the relation between the fields: DebtLedger.CustomerId - Partner.Id</summary>
		public virtual IEntityRelation PartnerEntityUsingCustomerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Partner", false, new[] { PartnerFields.Id, DebtLedgerFields.CustomerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDebtLedgerRelations
	{
		internal static readonly IEntityRelation DebtTypeEntityUsingDebtTypeIdStatic = new DebtLedgerRelations().DebtTypeEntityUsingDebtTypeId;
		internal static readonly IEntityRelation LiabilityDueEntityUsingLiabilityDuesIdStatic = new DebtLedgerRelations().LiabilityDueEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation PartnerEntityUsingCustomerIdStatic = new DebtLedgerRelations().PartnerEntityUsingCustomerId;

		/// <summary>CTor</summary>
		static StaticDebtLedgerRelations() { }
	}
}
