//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Depreciation'.<br/><br/></summary>
	[Serializable]
	public partial class DepreciationEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private AssetEntity _asset;
		private SourceEntity _source;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DepreciationEntityStaticMetaData _staticMetaData = new DepreciationEntityStaticMetaData();
		private static DepreciationRelations _relationsFactory = new DepreciationRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Asset</summary>
			public static readonly string Asset = "Asset";
			/// <summary>Member name Source</summary>
			public static readonly string Source = "Source";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DepreciationEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DepreciationEntityStaticMetaData()
			{
				SetEntityCoreInfo("DepreciationEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.DepreciationEntity, typeof(DepreciationEntity), typeof(DepreciationEntityFactory), false);
				AddNavigatorMetaData<DepreciationEntity, AssetEntity>("Asset", "Depreciations", (a, b) => a._asset = b, a => a._asset, (a, b) => a.Asset = b, DataAccess.RelationClasses.StaticDepreciationRelations.AssetEntityUsingAssetIdStatic, ()=>new DepreciationRelations().AssetEntityUsingAssetId, null, new int[] { (int)DepreciationFieldIndex.AssetId }, null, true, (int)DataAccess.EntityType.AssetEntity);
				AddNavigatorMetaData<DepreciationEntity, SourceEntity>("Source", "Depreciations", (a, b) => a._source = b, a => a._source, (a, b) => a.Source = b, DataAccess.RelationClasses.StaticDepreciationRelations.SourceEntityUsingSrcodeStatic, ()=>new DepreciationRelations().SourceEntityUsingSrcode, null, new int[] { (int)DepreciationFieldIndex.Srcode }, null, true, (int)DataAccess.EntityType.SourceEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DepreciationEntity()
		{
		}

		/// <summary> CTor</summary>
		public DepreciationEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DepreciationEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DepreciationEntity</param>
		public DepreciationEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Depreciation which data should be fetched into this Depreciation object</param>
		public DepreciationEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Depreciation which data should be fetched into this Depreciation object</param>
		/// <param name="validator">The custom validator object for this DepreciationEntity</param>
		public DepreciationEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DepreciationEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Asset' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAsset() { return CreateRelationInfoForNavigator("Asset"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Source' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSource() { return CreateRelationInfoForNavigator("Source"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DepreciationEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DepreciationRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Asset' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAsset { get { return _staticMetaData.GetPrefetchPathElement("Asset", CommonEntityBase.CreateEntityCollection<AssetEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Source' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSource { get { return _staticMetaData.GetPrefetchPathElement("Source", CommonEntityBase.CreateEntityCollection<SourceEntity>()); } }

		/// <summary>The Amount property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Amount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Amount
		{
			get { return (Nullable<System.Double>)GetValue((int)DepreciationFieldIndex.Amount, false); }
			set { SetValue((int)DepreciationFieldIndex.Amount, value); }
		}

		/// <summary>The AssetId property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."AssetId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AssetId
		{
			get { return (System.String)GetValue((int)DepreciationFieldIndex.AssetId, true); }
			set { SetValue((int)DepreciationFieldIndex.AssetId, value); }
		}

		/// <summary>The Flag property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Flag".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Flag
		{
			get { return (Nullable<System.Int32>)GetValue((int)DepreciationFieldIndex.Flag, false); }
			set { SetValue((int)DepreciationFieldIndex.Flag, value); }
		}

		/// <summary>The Id property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)DepreciationFieldIndex.Id, true); }
			set { SetValue((int)DepreciationFieldIndex.Id, value); }
		}

		/// <summary>The Rest property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Rest".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Rest
		{
			get { return (Nullable<System.Double>)GetValue((int)DepreciationFieldIndex.Rest, false); }
			set { SetValue((int)DepreciationFieldIndex.Rest, value); }
		}

		/// <summary>The Restqty property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Restqty".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Restqty
		{
			get { return (Nullable<System.Double>)GetValue((int)DepreciationFieldIndex.Restqty, false); }
			set { SetValue((int)DepreciationFieldIndex.Restqty, value); }
		}

		/// <summary>The Srcode property of the Entity Depreciation<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Depreciation"."Srcode".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Srcode
		{
			get { return (System.String)GetValue((int)DepreciationFieldIndex.Srcode, true); }
			set { SetValue((int)DepreciationFieldIndex.Srcode, value); }
		}

		/// <summary>Gets / sets related entity of type 'AssetEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual AssetEntity Asset
		{
			get { return _asset; }
			set { SetSingleRelatedEntityNavigator(value, "Asset"); }
		}

		/// <summary>Gets / sets related entity of type 'SourceEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SourceEntity Source
		{
			get { return _source; }
			set { SetSingleRelatedEntityNavigator(value, "Source"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum DepreciationFieldIndex
	{
		///<summary>Amount. </summary>
		Amount,
		///<summary>AssetId. </summary>
		AssetId,
		///<summary>Flag. </summary>
		Flag,
		///<summary>Id. </summary>
		Id,
		///<summary>Rest. </summary>
		Rest,
		///<summary>Restqty. </summary>
		Restqty,
		///<summary>Srcode. </summary>
		Srcode,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Depreciation. </summary>
	public partial class DepreciationRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between DepreciationEntity and AssetEntity over the m:1 relation they have, using the relation between the fields: Depreciation.AssetId - Asset.AssetId</summary>
		public virtual IEntityRelation AssetEntityUsingAssetId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Asset", false, new[] { AssetFields.AssetId, DepreciationFields.AssetId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between DepreciationEntity and SourceEntity over the m:1 relation they have, using the relation between the fields: Depreciation.Srcode - Source.Srcode</summary>
		public virtual IEntityRelation SourceEntityUsingSrcode
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Source", false, new[] { SourceFields.Srcode, DepreciationFields.Srcode }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDepreciationRelations
	{
		internal static readonly IEntityRelation AssetEntityUsingAssetIdStatic = new DepreciationRelations().AssetEntityUsingAssetId;
		internal static readonly IEntityRelation SourceEntityUsingSrcodeStatic = new DepreciationRelations().SourceEntityUsingSrcode;

		/// <summary>CTor</summary>
		static StaticDepreciationRelations() { }
	}
}
