//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ExchangeRate'.<br/><br/></summary>
	[Serializable]
	public partial class ExchangeRateEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private CurrencyEntity _currency;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ExchangeRateEntityStaticMetaData _staticMetaData = new ExchangeRateEntityStaticMetaData();
		private static ExchangeRateRelations _relationsFactory = new ExchangeRateRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Currency</summary>
			public static readonly string Currency = "Currency";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ExchangeRateEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ExchangeRateEntityStaticMetaData()
			{
				SetEntityCoreInfo("ExchangeRateEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.ExchangeRateEntity, typeof(ExchangeRateEntity), typeof(ExchangeRateEntityFactory), false);
				AddNavigatorMetaData<ExchangeRateEntity, CurrencyEntity>("Currency", "ExchangeRates", (a, b) => a._currency = b, a => a._currency, (a, b) => a.Currency = b, DataAccess.RelationClasses.StaticExchangeRateRelations.CurrencyEntityUsingCurrencyIdStatic, ()=>new ExchangeRateRelations().CurrencyEntityUsingCurrencyId, null, new int[] { (int)ExchangeRateFieldIndex.CurrencyId }, null, true, (int)DataAccess.EntityType.CurrencyEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ExchangeRateEntity()
		{
		}

		/// <summary> CTor</summary>
		public ExchangeRateEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ExchangeRateEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ExchangeRateEntity</param>
		public ExchangeRateEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ExchangeRate which data should be fetched into this ExchangeRate object</param>
		public ExchangeRateEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ExchangeRate which data should be fetched into this ExchangeRate object</param>
		/// <param name="validator">The custom validator object for this ExchangeRateEntity</param>
		public ExchangeRateEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ExchangeRateEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: CurrencyId , Month .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCCurrencyIdMonth()
		{
			var filter = new PredicateExpression();
			filter.Add(DataAccess.HelperClasses.ExchangeRateFields.CurrencyId == this.Fields.GetCurrentValue((int)ExchangeRateFieldIndex.CurrencyId));
			filter.Add(DataAccess.HelperClasses.ExchangeRateFields.Month == this.Fields.GetCurrentValue((int)ExchangeRateFieldIndex.Month));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Currency' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCurrency() { return CreateRelationInfoForNavigator("Currency"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ExchangeRateEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ExchangeRateRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Currency' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCurrency { get { return _staticMetaData.GetPrefetchPathElement("Currency", CommonEntityBase.CreateEntityCollection<CurrencyEntity>()); } }

		/// <summary>The CurrencyId property of the Entity ExchangeRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ExchangeRate"."CurrencyId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String CurrencyId
		{
			get { return (System.String)GetValue((int)ExchangeRateFieldIndex.CurrencyId, true); }
			set { SetValue((int)ExchangeRateFieldIndex.CurrencyId, value); }
		}

		/// <summary>The ExchangeRate property of the Entity ExchangeRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ExchangeRate"."ExchangeRate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> ExchangeRate
		{
			get { return (Nullable<System.Double>)GetValue((int)ExchangeRateFieldIndex.ExchangeRate, false); }
			set { SetValue((int)ExchangeRateFieldIndex.ExchangeRate, value); }
		}

		/// <summary>The Id property of the Entity ExchangeRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ExchangeRate"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ExchangeRateFieldIndex.Id, true); }
			set { SetValue((int)ExchangeRateFieldIndex.Id, value); }
		}

		/// <summary>The Month property of the Entity ExchangeRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ExchangeRate"."Month".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Month
		{
			get { return (System.Int16)GetValue((int)ExchangeRateFieldIndex.Month, true); }
			set { SetValue((int)ExchangeRateFieldIndex.Month, value); }
		}

		/// <summary>Gets / sets related entity of type 'CurrencyEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CurrencyEntity Currency
		{
			get { return _currency; }
			set { SetSingleRelatedEntityNavigator(value, "Currency"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum ExchangeRateFieldIndex
	{
		///<summary>CurrencyId. </summary>
		CurrencyId,
		///<summary>ExchangeRate. </summary>
		ExchangeRate,
		///<summary>Id. </summary>
		Id,
		///<summary>Month. </summary>
		Month,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ExchangeRate. </summary>
	public partial class ExchangeRateRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ExchangeRateEntity and CurrencyEntity over the m:1 relation they have, using the relation between the fields: ExchangeRate.CurrencyId - Currency.CurrencyId</summary>
		public virtual IEntityRelation CurrencyEntityUsingCurrencyId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Currency", false, new[] { CurrencyFields.CurrencyId, ExchangeRateFields.CurrencyId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticExchangeRateRelations
	{
		internal static readonly IEntityRelation CurrencyEntityUsingCurrencyIdStatic = new ExchangeRateRelations().CurrencyEntityUsingCurrencyId;

		/// <summary>CTor</summary>
		static StaticExchangeRateRelations() { }
	}
}
