//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'FinancialMonth'.<br/><br/></summary>
	[Serializable]
	public partial class FinancialMonthEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static FinancialMonthEntityStaticMetaData _staticMetaData = new FinancialMonthEntityStaticMetaData();
		private static FinancialMonthRelations _relationsFactory = new FinancialMonthRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class FinancialMonthEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public FinancialMonthEntityStaticMetaData()
			{
				SetEntityCoreInfo("FinancialMonthEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.FinancialMonthEntity, typeof(FinancialMonthEntity), typeof(FinancialMonthEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static FinancialMonthEntity()
		{
		}

		/// <summary> CTor</summary>
		public FinancialMonthEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public FinancialMonthEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this FinancialMonthEntity</param>
		public FinancialMonthEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="month">PK value for FinancialMonth which data should be fetched into this FinancialMonth object</param>
		public FinancialMonthEntity(System.Int32 month) : this(month, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="month">PK value for FinancialMonth which data should be fetched into this FinancialMonth object</param>
		/// <param name="validator">The custom validator object for this FinancialMonthEntity</param>
		public FinancialMonthEntity(System.Int32 month, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Month = month;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected FinancialMonthEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this FinancialMonthEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static FinancialMonthRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Month property of the Entity FinancialMonth<br/><br/></summary>
		/// <remarks>Mapped on  table field: "FinancialMonth"."Month".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Month
		{
			get { return (System.Int32)GetValue((int)FinancialMonthFieldIndex.Month, true); }
			set { SetValue((int)FinancialMonthFieldIndex.Month, value); }
		}

		/// <summary>The MonthName property of the Entity FinancialMonth<br/><br/></summary>
		/// <remarks>Mapped on  table field: "FinancialMonth"."MonthName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MonthName
		{
			get { return (System.String)GetValue((int)FinancialMonthFieldIndex.MonthName, true); }
			set { SetValue((int)FinancialMonthFieldIndex.MonthName, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum FinancialMonthFieldIndex
	{
		///<summary>Month. </summary>
		Month,
		///<summary>MonthName. </summary>
		MonthName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: FinancialMonth. </summary>
	public partial class FinancialMonthRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticFinancialMonthRelations
	{

		/// <summary>CTor</summary>
		static StaticFinancialMonthRelations() { }
	}
}
