//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'InterestRate'.<br/><br/></summary>
	[Serializable]
	public partial class InterestRateEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AssetTrackingEntity> _assetTrackings;
		private EntityCollection<AssetTrackingDepreciationEntity> _assetTrackingDepreciations;
		private EntityCollection<InterestDetailEntity> _interestDetails;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static InterestRateEntityStaticMetaData _staticMetaData = new InterestRateEntityStaticMetaData();
		private static InterestRateRelations _relationsFactory = new InterestRateRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AssetTrackings</summary>
			public static readonly string AssetTrackings = "AssetTrackings";
			/// <summary>Member name AssetTrackingDepreciations</summary>
			public static readonly string AssetTrackingDepreciations = "AssetTrackingDepreciations";
			/// <summary>Member name InterestDetails</summary>
			public static readonly string InterestDetails = "InterestDetails";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class InterestRateEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public InterestRateEntityStaticMetaData()
			{
				SetEntityCoreInfo("InterestRateEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.InterestRateEntity, typeof(InterestRateEntity), typeof(InterestRateEntityFactory), false);
				AddNavigatorMetaData<InterestRateEntity, EntityCollection<AssetTrackingEntity>>("AssetTrackings", a => a._assetTrackings, (a, b) => a._assetTrackings = b, a => a.AssetTrackings, () => new InterestRateRelations().AssetTrackingEntityUsingEnddate, typeof(AssetTrackingEntity), (int)DataAccess.EntityType.AssetTrackingEntity);
				AddNavigatorMetaData<InterestRateEntity, EntityCollection<AssetTrackingDepreciationEntity>>("AssetTrackingDepreciations", a => a._assetTrackingDepreciations, (a, b) => a._assetTrackingDepreciations = b, a => a.AssetTrackingDepreciations, () => new InterestRateRelations().AssetTrackingDepreciationEntityUsingEnddate, typeof(AssetTrackingDepreciationEntity), (int)DataAccess.EntityType.AssetTrackingDepreciationEntity);
				AddNavigatorMetaData<InterestRateEntity, EntityCollection<InterestDetailEntity>>("InterestDetails", a => a._interestDetails, (a, b) => a._interestDetails = b, a => a.InterestDetails, () => new InterestRateRelations().InterestDetailEntityUsingEnddate, typeof(InterestDetailEntity), (int)DataAccess.EntityType.InterestDetailEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static InterestRateEntity()
		{
		}

		/// <summary> CTor</summary>
		public InterestRateEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public InterestRateEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this InterestRateEntity</param>
		public InterestRateEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="enddate">PK value for InterestRate which data should be fetched into this InterestRate object</param>
		public InterestRateEntity(System.DateTime enddate) : this(enddate, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="enddate">PK value for InterestRate which data should be fetched into this InterestRate object</param>
		/// <param name="validator">The custom validator object for this InterestRateEntity</param>
		public InterestRateEntity(System.DateTime enddate, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Enddate = enddate;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected InterestRateEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AssetTracking' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAssetTrackings() { return CreateRelationInfoForNavigator("AssetTrackings"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AssetTrackingDepreciation' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAssetTrackingDepreciations() { return CreateRelationInfoForNavigator("AssetTrackingDepreciations"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InterestDetail' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInterestDetails() { return CreateRelationInfoForNavigator("InterestDetails"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this InterestRateEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static InterestRateRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AssetTracking' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAssetTrackings { get { return _staticMetaData.GetPrefetchPathElement("AssetTrackings", CommonEntityBase.CreateEntityCollection<AssetTrackingEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AssetTrackingDepreciation' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAssetTrackingDepreciations { get { return _staticMetaData.GetPrefetchPathElement("AssetTrackingDepreciations", CommonEntityBase.CreateEntityCollection<AssetTrackingDepreciationEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InterestDetail' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInterestDetails { get { return _staticMetaData.GetPrefetchPathElement("InterestDetails", CommonEntityBase.CreateEntityCollection<InterestDetailEntity>()); } }

		/// <summary>The Enddate property of the Entity InterestRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InterestRate"."Enddate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.DateTime Enddate
		{
			get { return (System.DateTime)GetValue((int)InterestRateFieldIndex.Enddate, true); }
			set { SetValue((int)InterestRateFieldIndex.Enddate, value); }
		}

		/// <summary>The Rate property of the Entity InterestRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InterestRate"."Rate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Rate
		{
			get { return (Nullable<System.Double>)GetValue((int)InterestRateFieldIndex.Rate, false); }
			set { SetValue((int)InterestRateFieldIndex.Rate, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AssetTrackingEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AssetTrackingEntity))]
		public virtual EntityCollection<AssetTrackingEntity> AssetTrackings { get { return GetOrCreateEntityCollection<AssetTrackingEntity, AssetTrackingEntityFactory>("InterestRate", true, false, ref _assetTrackings); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'AssetTrackingDepreciationEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AssetTrackingDepreciationEntity))]
		public virtual EntityCollection<AssetTrackingDepreciationEntity> AssetTrackingDepreciations { get { return GetOrCreateEntityCollection<AssetTrackingDepreciationEntity, AssetTrackingDepreciationEntityFactory>("InterestRate", true, false, ref _assetTrackingDepreciations); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'InterestDetailEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InterestDetailEntity))]
		public virtual EntityCollection<InterestDetailEntity> InterestDetails { get { return GetOrCreateEntityCollection<InterestDetailEntity, InterestDetailEntityFactory>("InterestRate", true, false, ref _interestDetails); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum InterestRateFieldIndex
	{
		///<summary>Enddate. </summary>
		Enddate,
		///<summary>Rate. </summary>
		Rate,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: InterestRate. </summary>
	public partial class InterestRateRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between InterestRateEntity and AssetTrackingEntity over the 1:n relation they have, using the relation between the fields: InterestRate.Enddate - AssetTracking.Enddate</summary>
		public virtual IEntityRelation AssetTrackingEntityUsingEnddate
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AssetTrackings", true, new[] { InterestRateFields.Enddate, AssetTrackingFields.Enddate }); }
		}

		/// <summary>Returns a new IEntityRelation object, between InterestRateEntity and AssetTrackingDepreciationEntity over the 1:n relation they have, using the relation between the fields: InterestRate.Enddate - AssetTrackingDepreciation.Enddate</summary>
		public virtual IEntityRelation AssetTrackingDepreciationEntityUsingEnddate
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AssetTrackingDepreciations", true, new[] { InterestRateFields.Enddate, AssetTrackingDepreciationFields.Enddate }); }
		}

		/// <summary>Returns a new IEntityRelation object, between InterestRateEntity and InterestDetailEntity over the 1:n relation they have, using the relation between the fields: InterestRate.Enddate - InterestDetail.Enddate</summary>
		public virtual IEntityRelation InterestDetailEntityUsingEnddate
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "InterestDetails", true, new[] { InterestRateFields.Enddate, InterestDetailFields.Enddate }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticInterestRateRelations
	{
		internal static readonly IEntityRelation AssetTrackingEntityUsingEnddateStatic = new InterestRateRelations().AssetTrackingEntityUsingEnddate;
		internal static readonly IEntityRelation AssetTrackingDepreciationEntityUsingEnddateStatic = new InterestRateRelations().AssetTrackingDepreciationEntityUsingEnddate;
		internal static readonly IEntityRelation InterestDetailEntityUsingEnddateStatic = new InterestRateRelations().InterestDetailEntityUsingEnddate;

		/// <summary>CTor</summary>
		static StaticInterestRateRelations() { }
	}
}
