//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'InventoryLedger'.<br/><br/></summary>
	[Serializable]
	public partial class InventoryLedgerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static InventoryLedgerEntityStaticMetaData _staticMetaData = new InventoryLedgerEntityStaticMetaData();
		private static InventoryLedgerRelations _relationsFactory = new InventoryLedgerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class InventoryLedgerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public InventoryLedgerEntityStaticMetaData()
			{
				SetEntityCoreInfo("InventoryLedgerEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.InventoryLedgerEntity, typeof(InventoryLedgerEntity), typeof(InventoryLedgerEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static InventoryLedgerEntity()
		{
		}

		/// <summary> CTor</summary>
		public InventoryLedgerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public InventoryLedgerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this InventoryLedgerEntity</param>
		public InventoryLedgerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for InventoryLedger which data should be fetched into this InventoryLedger object</param>
		public InventoryLedgerEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for InventoryLedger which data should be fetched into this InventoryLedger object</param>
		/// <param name="validator">The custom validator object for this InventoryLedgerEntity</param>
		public InventoryLedgerEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected InventoryLedgerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this InventoryLedgerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static InventoryLedgerRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Camount property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Camount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Camount
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Camount, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Camount, value); }
		}

		/// <summary>The Contents property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Contents".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Contents
		{
			get { return (System.String)GetValue((int)InventoryLedgerFieldIndex.Contents, true); }
			set { SetValue((int)InventoryLedgerFieldIndex.Contents, value); }
		}

		/// <summary>The Cprice property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Cprice".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Cprice
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Cprice, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Cprice, value); }
		}

		/// <summary>The Cquantity property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Cquantity".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Cquantity
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Cquantity, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Cquantity, value); }
		}

		/// <summary>The Damount property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Damount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Damount
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Damount, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Damount, value); }
		}

		/// <summary>The Dprice property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Dprice".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Dprice
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Dprice, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Dprice, value); }
		}

		/// <summary>The Dquantity property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Dquantity".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Dquantity
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Dquantity, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Dquantity, value); }
		}

		/// <summary>The Endamount property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Endamount".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endamount
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Endamount, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Endamount, value); }
		}

		/// <summary>The Endqty property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Endqty".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Endqty
		{
			get { return (Nullable<System.Double>)GetValue((int)InventoryLedgerFieldIndex.Endqty, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.Endqty, value); }
		}

		/// <summary>The Id property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)InventoryLedgerFieldIndex.Id, true); }
			set { SetValue((int)InventoryLedgerFieldIndex.Id, value); }
		}

		/// <summary>The JournalVoucherId property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."JournalVoucherId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> JournalVoucherId
		{
			get { return (Nullable<System.Int32>)GetValue((int)InventoryLedgerFieldIndex.JournalVoucherId, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.JournalVoucherId, value); }
		}

		/// <summary>The VoucherDate property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."VoucherDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> VoucherDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)InventoryLedgerFieldIndex.VoucherDate, false); }
			set { SetValue((int)InventoryLedgerFieldIndex.VoucherDate, value); }
		}

		/// <summary>The VoucherNo property of the Entity InventoryLedger<br/><br/></summary>
		/// <remarks>Mapped on  table field: "InventoryLedger"."VoucherNo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VoucherNo
		{
			get { return (System.String)GetValue((int)InventoryLedgerFieldIndex.VoucherNo, true); }
			set { SetValue((int)InventoryLedgerFieldIndex.VoucherNo, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum InventoryLedgerFieldIndex
	{
		///<summary>Camount. </summary>
		Camount,
		///<summary>Contents. </summary>
		Contents,
		///<summary>Cprice. </summary>
		Cprice,
		///<summary>Cquantity. </summary>
		Cquantity,
		///<summary>Damount. </summary>
		Damount,
		///<summary>Dprice. </summary>
		Dprice,
		///<summary>Dquantity. </summary>
		Dquantity,
		///<summary>Endamount. </summary>
		Endamount,
		///<summary>Endqty. </summary>
		Endqty,
		///<summary>Id. </summary>
		Id,
		///<summary>JournalVoucherId. </summary>
		JournalVoucherId,
		///<summary>VoucherDate. </summary>
		VoucherDate,
		///<summary>VoucherNo. </summary>
		VoucherNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: InventoryLedger. </summary>
	public partial class InventoryLedgerRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticInventoryLedgerRelations
	{

		/// <summary>CTor</summary>
		static StaticInventoryLedgerRelations() { }
	}
}
