//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'JournalVoucher'.<br/><br/></summary>
	[Serializable]
	public partial class JournalVoucherEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<JournalEntryEntity> _journalEntries;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static JournalVoucherEntityStaticMetaData _staticMetaData = new JournalVoucherEntityStaticMetaData();
		private static JournalVoucherRelations _relationsFactory = new JournalVoucherRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name JournalEntries</summary>
			public static readonly string JournalEntries = "JournalEntries";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class JournalVoucherEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public JournalVoucherEntityStaticMetaData()
			{
				SetEntityCoreInfo("JournalVoucherEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.JournalVoucherEntity, typeof(JournalVoucherEntity), typeof(JournalVoucherEntityFactory), false);
				AddNavigatorMetaData<JournalVoucherEntity, EntityCollection<JournalEntryEntity>>("JournalEntries", a => a._journalEntries, (a, b) => a._journalEntries = b, a => a.JournalEntries, () => new JournalVoucherRelations().JournalEntryEntityUsingJournalVoucherId, typeof(JournalEntryEntity), (int)DataAccess.EntityType.JournalEntryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static JournalVoucherEntity()
		{
		}

		/// <summary> CTor</summary>
		public JournalVoucherEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public JournalVoucherEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this JournalVoucherEntity</param>
		public JournalVoucherEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for JournalVoucher which data should be fetched into this JournalVoucher object</param>
		public JournalVoucherEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for JournalVoucher which data should be fetched into this JournalVoucher object</param>
		/// <param name="validator">The custom validator object for this JournalVoucherEntity</param>
		public JournalVoucherEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected JournalVoucherEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'JournalEntry' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoJournalEntries() { return CreateRelationInfoForNavigator("JournalEntries"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this JournalVoucherEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static JournalVoucherRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'JournalEntry' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathJournalEntries { get { return _staticMetaData.GetPrefetchPathElement("JournalEntries", CommonEntityBase.CreateEntityCollection<JournalEntryEntity>()); } }

		/// <summary>The Bookflag property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Bookflag".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Bookflag
		{
			get { return (System.Boolean)GetValue((int)JournalVoucherFieldIndex.Bookflag, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Bookflag, value); }
		}

		/// <summary>The Contents property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Contents".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Contents
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Contents, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Contents, value); }
		}

		/// <summary>The Flag property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Flag".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Flag
		{
			get { return (System.Boolean)GetValue((int)JournalVoucherFieldIndex.Flag, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Flag, value); }
		}

		/// <summary>The Id property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)JournalVoucherFieldIndex.Id, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Id, value); }
		}

		/// <summary>The Invoicesnumber property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Invoicesnumber".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Invoicesnumber
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Invoicesnumber, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Invoicesnumber, value); }
		}

		/// <summary>The Marked property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Marked".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Marked
		{
			get { return (System.Boolean)GetValue((int)JournalVoucherFieldIndex.Marked, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Marked, value); }
		}

		/// <summary>The Outtableflag property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Outtableflag".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Outtableflag
		{
			get { return (System.Boolean)GetValue((int)JournalVoucherFieldIndex.Outtableflag, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Outtableflag, value); }
		}

		/// <summary>The Paymentacc property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Paymentacc".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Paymentacc
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Paymentacc, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Paymentacc, value); }
		}

		/// <summary>The Paymentbank property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Paymentbank".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Paymentbank
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Paymentbank, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Paymentbank, value); }
		}

		/// <summary>The Personaddress property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Personaddress".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Personaddress
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Personaddress, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Personaddress, value); }
		}

		/// <summary>The Personname property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Personname".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Personname
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Personname, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Personname, value); }
		}

		/// <summary>The Recievedacc property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Recievedacc".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Recievedacc
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Recievedacc, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Recievedacc, value); }
		}

		/// <summary>The Recievedbank property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Recievedbank".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Recievedbank
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Recievedbank, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Recievedbank, value); }
		}

		/// <summary>The Recievedcorp property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."Recievedcorp".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Recievedcorp
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.Recievedcorp, true); }
			set { SetValue((int)JournalVoucherFieldIndex.Recievedcorp, value); }
		}

		/// <summary>The VoucherDate property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."VoucherDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> VoucherDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)JournalVoucherFieldIndex.VoucherDate, false); }
			set { SetValue((int)JournalVoucherFieldIndex.VoucherDate, value); }
		}

		/// <summary>The VoucherNo property of the Entity JournalVoucher<br/><br/></summary>
		/// <remarks>Mapped on  table field: "JournalVoucher"."VoucherNo".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String VoucherNo
		{
			get { return (System.String)GetValue((int)JournalVoucherFieldIndex.VoucherNo, true); }
			set { SetValue((int)JournalVoucherFieldIndex.VoucherNo, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'JournalEntryEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(JournalEntryEntity))]
		public virtual EntityCollection<JournalEntryEntity> JournalEntries { get { return GetOrCreateEntityCollection<JournalEntryEntity, JournalEntryEntityFactory>("JournalVoucher", true, false, ref _journalEntries); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum JournalVoucherFieldIndex
	{
		///<summary>Bookflag. </summary>
		Bookflag,
		///<summary>Contents. </summary>
		Contents,
		///<summary>Flag. </summary>
		Flag,
		///<summary>Id. </summary>
		Id,
		///<summary>Invoicesnumber. </summary>
		Invoicesnumber,
		///<summary>Marked. </summary>
		Marked,
		///<summary>Outtableflag. </summary>
		Outtableflag,
		///<summary>Paymentacc. </summary>
		Paymentacc,
		///<summary>Paymentbank. </summary>
		Paymentbank,
		///<summary>Personaddress. </summary>
		Personaddress,
		///<summary>Personname. </summary>
		Personname,
		///<summary>Recievedacc. </summary>
		Recievedacc,
		///<summary>Recievedbank. </summary>
		Recievedbank,
		///<summary>Recievedcorp. </summary>
		Recievedcorp,
		///<summary>VoucherDate. </summary>
		VoucherDate,
		///<summary>VoucherNo. </summary>
		VoucherNo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: JournalVoucher. </summary>
	public partial class JournalVoucherRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between JournalVoucherEntity and JournalEntryEntity over the 1:n relation they have, using the relation between the fields: JournalVoucher.Id - JournalEntry.JournalVoucherId</summary>
		public virtual IEntityRelation JournalEntryEntityUsingJournalVoucherId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "JournalEntries", true, new[] { JournalVoucherFields.Id, JournalEntryFields.JournalVoucherId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticJournalVoucherRelations
	{
		internal static readonly IEntityRelation JournalEntryEntityUsingJournalVoucherIdStatic = new JournalVoucherRelations().JournalEntryEntityUsingJournalVoucherId;

		/// <summary>CTor</summary>
		static StaticJournalVoucherRelations() { }
	}
}
