//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'LiabilityDue'.<br/><br/></summary>
	[Serializable]
	public partial class LiabilityDueEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<CustomerExportLineEntity> _customerExportLines;
		private EntityCollection<DebtDetailEntity> _debtDetails;
		private EntityCollection<DebtLedgerEntity> _debtLedgers;
		private EntityCollection<InterestEntity> _interests;
		private DebtTypeEntity _debtType;
		private PartnerEntity _partner;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static LiabilityDueEntityStaticMetaData _staticMetaData = new LiabilityDueEntityStaticMetaData();
		private static LiabilityDueRelations _relationsFactory = new LiabilityDueRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name DebtType</summary>
			public static readonly string DebtType = "DebtType";
			/// <summary>Member name Partner</summary>
			public static readonly string Partner = "Partner";
			/// <summary>Member name CustomerExportLines</summary>
			public static readonly string CustomerExportLines = "CustomerExportLines";
			/// <summary>Member name DebtDetails</summary>
			public static readonly string DebtDetails = "DebtDetails";
			/// <summary>Member name DebtLedgers</summary>
			public static readonly string DebtLedgers = "DebtLedgers";
			/// <summary>Member name Interests</summary>
			public static readonly string Interests = "Interests";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class LiabilityDueEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public LiabilityDueEntityStaticMetaData()
			{
				SetEntityCoreInfo("LiabilityDueEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.LiabilityDueEntity, typeof(LiabilityDueEntity), typeof(LiabilityDueEntityFactory), false);
				AddNavigatorMetaData<LiabilityDueEntity, EntityCollection<CustomerExportLineEntity>>("CustomerExportLines", a => a._customerExportLines, (a, b) => a._customerExportLines = b, a => a.CustomerExportLines, () => new LiabilityDueRelations().CustomerExportLineEntityUsingLiabilityDuesId, typeof(CustomerExportLineEntity), (int)DataAccess.EntityType.CustomerExportLineEntity);
				AddNavigatorMetaData<LiabilityDueEntity, EntityCollection<DebtDetailEntity>>("DebtDetails", a => a._debtDetails, (a, b) => a._debtDetails = b, a => a.DebtDetails, () => new LiabilityDueRelations().DebtDetailEntityUsingLiabilityDuesId, typeof(DebtDetailEntity), (int)DataAccess.EntityType.DebtDetailEntity);
				AddNavigatorMetaData<LiabilityDueEntity, EntityCollection<DebtLedgerEntity>>("DebtLedgers", a => a._debtLedgers, (a, b) => a._debtLedgers = b, a => a.DebtLedgers, () => new LiabilityDueRelations().DebtLedgerEntityUsingLiabilityDuesId, typeof(DebtLedgerEntity), (int)DataAccess.EntityType.DebtLedgerEntity);
				AddNavigatorMetaData<LiabilityDueEntity, EntityCollection<InterestEntity>>("Interests", a => a._interests, (a, b) => a._interests = b, a => a.Interests, () => new LiabilityDueRelations().InterestEntityUsingLiabilityDuesId, typeof(InterestEntity), (int)DataAccess.EntityType.InterestEntity);
				AddNavigatorMetaData<LiabilityDueEntity, DebtTypeEntity>("DebtType", "LiabilityDues", (a, b) => a._debtType = b, a => a._debtType, (a, b) => a.DebtType = b, DataAccess.RelationClasses.StaticLiabilityDueRelations.DebtTypeEntityUsingDebtTypeIdStatic, ()=>new LiabilityDueRelations().DebtTypeEntityUsingDebtTypeId, null, new int[] { (int)LiabilityDueFieldIndex.DebtTypeId }, null, true, (int)DataAccess.EntityType.DebtTypeEntity);
				AddNavigatorMetaData<LiabilityDueEntity, PartnerEntity>("Partner", "LiabilityDues", (a, b) => a._partner = b, a => a._partner, (a, b) => a.Partner = b, DataAccess.RelationClasses.StaticLiabilityDueRelations.PartnerEntityUsingCustomerIdStatic, ()=>new LiabilityDueRelations().PartnerEntityUsingCustomerId, null, new int[] { (int)LiabilityDueFieldIndex.CustomerId }, null, true, (int)DataAccess.EntityType.PartnerEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static LiabilityDueEntity()
		{
		}

		/// <summary> CTor</summary>
		public LiabilityDueEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public LiabilityDueEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this LiabilityDueEntity</param>
		public LiabilityDueEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LiabilityDue which data should be fetched into this LiabilityDue object</param>
		public LiabilityDueEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for LiabilityDue which data should be fetched into this LiabilityDue object</param>
		/// <param name="validator">The custom validator object for this LiabilityDueEntity</param>
		public LiabilityDueEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected LiabilityDueEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: CustomerId , DebtTypeId .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCCustomerIdDebtTypeId()
		{
			var filter = new PredicateExpression();
			filter.Add(DataAccess.HelperClasses.LiabilityDueFields.CustomerId == this.Fields.GetCurrentValue((int)LiabilityDueFieldIndex.CustomerId));
			filter.Add(DataAccess.HelperClasses.LiabilityDueFields.DebtTypeId == this.Fields.GetCurrentValue((int)LiabilityDueFieldIndex.DebtTypeId));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CustomerExportLine' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomerExportLines() { return CreateRelationInfoForNavigator("CustomerExportLines"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'DebtDetail' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtDetails() { return CreateRelationInfoForNavigator("DebtDetails"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'DebtLedger' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtLedgers() { return CreateRelationInfoForNavigator("DebtLedgers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Interest' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInterests() { return CreateRelationInfoForNavigator("Interests"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'DebtType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtType() { return CreateRelationInfoForNavigator("DebtType"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Partner' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPartner() { return CreateRelationInfoForNavigator("Partner"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this LiabilityDueEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static LiabilityDueRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CustomerExportLine' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomerExportLines { get { return _staticMetaData.GetPrefetchPathElement("CustomerExportLines", CommonEntityBase.CreateEntityCollection<CustomerExportLineEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtDetail' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtDetails { get { return _staticMetaData.GetPrefetchPathElement("DebtDetails", CommonEntityBase.CreateEntityCollection<DebtDetailEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtLedger' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtLedgers { get { return _staticMetaData.GetPrefetchPathElement("DebtLedgers", CommonEntityBase.CreateEntityCollection<DebtLedgerEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Interest' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInterests { get { return _staticMetaData.GetPrefetchPathElement("Interests", CommonEntityBase.CreateEntityCollection<InterestEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtType { get { return _staticMetaData.GetPrefetchPathElement("DebtType", CommonEntityBase.CreateEntityCollection<DebtTypeEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Partner' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPartner { get { return _staticMetaData.GetPrefetchPathElement("Partner", CommonEntityBase.CreateEntityCollection<PartnerEntity>()); } }

		/// <summary>The BeginDate property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."BeginDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> BeginDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LiabilityDueFieldIndex.BeginDate, false); }
			set { SetValue((int)LiabilityDueFieldIndex.BeginDate, value); }
		}

		/// <summary>The CustomerId property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."CustomerId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String CustomerId
		{
			get { return (System.String)GetValue((int)LiabilityDueFieldIndex.CustomerId, true); }
			set { SetValue((int)LiabilityDueFieldIndex.CustomerId, value); }
		}

		/// <summary>The DebtTypeId property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."DebtTypeId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DebtTypeId
		{
			get { return (System.String)GetValue((int)LiabilityDueFieldIndex.DebtTypeId, true); }
			set { SetValue((int)LiabilityDueFieldIndex.DebtTypeId, value); }
		}

		/// <summary>The EndDate property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."EndDate".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> EndDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LiabilityDueFieldIndex.EndDate, false); }
			set { SetValue((int)LiabilityDueFieldIndex.EndDate, value); }
		}

		/// <summary>The Feedbackrate property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Feedbackrate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Feedbackrate
		{
			get { return (Nullable<System.Double>)GetValue((int)LiabilityDueFieldIndex.Feedbackrate, false); }
			set { SetValue((int)LiabilityDueFieldIndex.Feedbackrate, value); }
		}

		/// <summary>The Id property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)LiabilityDueFieldIndex.Id, true); }
			set { SetValue((int)LiabilityDueFieldIndex.Id, value); }
		}

		/// <summary>The Interestrate property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Interestrate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Interestrate
		{
			get { return (Nullable<System.Double>)GetValue((int)LiabilityDueFieldIndex.Interestrate, false); }
			set { SetValue((int)LiabilityDueFieldIndex.Interestrate, value); }
		}

		/// <summary>The Outvatrate property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Outvatrate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Outvatrate
		{
			get { return (Nullable<System.Double>)GetValue((int)LiabilityDueFieldIndex.Outvatrate, false); }
			set { SetValue((int)LiabilityDueFieldIndex.Outvatrate, value); }
		}

		/// <summary>The Remark property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Remark".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Remark
		{
			get { return (System.String)GetValue((int)LiabilityDueFieldIndex.Remark, true); }
			set { SetValue((int)LiabilityDueFieldIndex.Remark, value); }
		}

		/// <summary>The Settledflag property of the Entity LiabilityDue<br/><br/></summary>
		/// <remarks>Mapped on  table field: "LiabilityDue"."Settledflag".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Settledflag
		{
			get { return (System.Boolean)GetValue((int)LiabilityDueFieldIndex.Settledflag, true); }
			set { SetValue((int)LiabilityDueFieldIndex.Settledflag, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CustomerExportLineEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CustomerExportLineEntity))]
		public virtual EntityCollection<CustomerExportLineEntity> CustomerExportLines { get { return GetOrCreateEntityCollection<CustomerExportLineEntity, CustomerExportLineEntityFactory>("LiabilityDue", true, false, ref _customerExportLines); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'DebtDetailEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(DebtDetailEntity))]
		public virtual EntityCollection<DebtDetailEntity> DebtDetails { get { return GetOrCreateEntityCollection<DebtDetailEntity, DebtDetailEntityFactory>("LiabilityDue", true, false, ref _debtDetails); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'DebtLedgerEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(DebtLedgerEntity))]
		public virtual EntityCollection<DebtLedgerEntity> DebtLedgers { get { return GetOrCreateEntityCollection<DebtLedgerEntity, DebtLedgerEntityFactory>("LiabilityDue", true, false, ref _debtLedgers); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'InterestEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InterestEntity))]
		public virtual EntityCollection<InterestEntity> Interests { get { return GetOrCreateEntityCollection<InterestEntity, InterestEntityFactory>("LiabilityDue", true, false, ref _interests); } }

		/// <summary>Gets / sets related entity of type 'DebtTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual DebtTypeEntity DebtType
		{
			get { return _debtType; }
			set { SetSingleRelatedEntityNavigator(value, "DebtType"); }
		}

		/// <summary>Gets / sets related entity of type 'PartnerEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PartnerEntity Partner
		{
			get { return _partner; }
			set { SetSingleRelatedEntityNavigator(value, "Partner"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum LiabilityDueFieldIndex
	{
		///<summary>BeginDate. </summary>
		BeginDate,
		///<summary>CustomerId. </summary>
		CustomerId,
		///<summary>DebtTypeId. </summary>
		DebtTypeId,
		///<summary>EndDate. </summary>
		EndDate,
		///<summary>Feedbackrate. </summary>
		Feedbackrate,
		///<summary>Id. </summary>
		Id,
		///<summary>Interestrate. </summary>
		Interestrate,
		///<summary>Outvatrate. </summary>
		Outvatrate,
		///<summary>Remark. </summary>
		Remark,
		///<summary>Settledflag. </summary>
		Settledflag,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: LiabilityDue. </summary>
	public partial class LiabilityDueRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and CustomerExportLineEntity over the 1:n relation they have, using the relation between the fields: LiabilityDue.Id - CustomerExportLine.LiabilityDuesId</summary>
		public virtual IEntityRelation CustomerExportLineEntityUsingLiabilityDuesId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CustomerExportLines", true, new[] { LiabilityDueFields.Id, CustomerExportLineFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and DebtDetailEntity over the 1:n relation they have, using the relation between the fields: LiabilityDue.Id - DebtDetail.LiabilityDuesId</summary>
		public virtual IEntityRelation DebtDetailEntityUsingLiabilityDuesId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DebtDetails", true, new[] { LiabilityDueFields.Id, DebtDetailFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and DebtLedgerEntity over the 1:n relation they have, using the relation between the fields: LiabilityDue.Id - DebtLedger.LiabilityDuesId</summary>
		public virtual IEntityRelation DebtLedgerEntityUsingLiabilityDuesId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DebtLedgers", true, new[] { LiabilityDueFields.Id, DebtLedgerFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and InterestEntity over the 1:n relation they have, using the relation between the fields: LiabilityDue.Id - Interest.LiabilityDuesId</summary>
		public virtual IEntityRelation InterestEntityUsingLiabilityDuesId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Interests", true, new[] { LiabilityDueFields.Id, InterestFields.LiabilityDuesId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and DebtTypeEntity over the m:1 relation they have, using the relation between the fields: LiabilityDue.DebtTypeId - DebtType.Id</summary>
		public virtual IEntityRelation DebtTypeEntityUsingDebtTypeId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "DebtType", false, new[] { DebtTypeFields.Id, LiabilityDueFields.DebtTypeId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between LiabilityDueEntity and PartnerEntity over the m:1 relation they have, using the relation between the fields: LiabilityDue.CustomerId - Partner.Id</summary>
		public virtual IEntityRelation PartnerEntityUsingCustomerId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Partner", false, new[] { PartnerFields.Id, LiabilityDueFields.CustomerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticLiabilityDueRelations
	{
		internal static readonly IEntityRelation CustomerExportLineEntityUsingLiabilityDuesIdStatic = new LiabilityDueRelations().CustomerExportLineEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation DebtDetailEntityUsingLiabilityDuesIdStatic = new LiabilityDueRelations().DebtDetailEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation DebtLedgerEntityUsingLiabilityDuesIdStatic = new LiabilityDueRelations().DebtLedgerEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation InterestEntityUsingLiabilityDuesIdStatic = new LiabilityDueRelations().InterestEntityUsingLiabilityDuesId;
		internal static readonly IEntityRelation DebtTypeEntityUsingDebtTypeIdStatic = new LiabilityDueRelations().DebtTypeEntityUsingDebtTypeId;
		internal static readonly IEntityRelation PartnerEntityUsingCustomerIdStatic = new LiabilityDueRelations().PartnerEntityUsingCustomerId;

		/// <summary>CTor</summary>
		static StaticLiabilityDueRelations() { }
	}
}
