//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'MaterialPrice'.<br/><br/></summary>
	[Serializable]
	public partial class MaterialPriceEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private InventoryItemEntity _inventoryItem;
		private WarehouseEntity _warehouse;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static MaterialPriceEntityStaticMetaData _staticMetaData = new MaterialPriceEntityStaticMetaData();
		private static MaterialPriceRelations _relationsFactory = new MaterialPriceRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name InventoryItem</summary>
			public static readonly string InventoryItem = "InventoryItem";
			/// <summary>Member name Warehouse</summary>
			public static readonly string Warehouse = "Warehouse";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class MaterialPriceEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public MaterialPriceEntityStaticMetaData()
			{
				SetEntityCoreInfo("MaterialPriceEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.MaterialPriceEntity, typeof(MaterialPriceEntity), typeof(MaterialPriceEntityFactory), false);
				AddNavigatorMetaData<MaterialPriceEntity, InventoryItemEntity>("InventoryItem", "MaterialPrices", (a, b) => a._inventoryItem = b, a => a._inventoryItem, (a, b) => a.InventoryItem = b, DataAccess.RelationClasses.StaticMaterialPriceRelations.InventoryItemEntityUsingMaterialIdStatic, ()=>new MaterialPriceRelations().InventoryItemEntityUsingMaterialId, null, new int[] { (int)MaterialPriceFieldIndex.MaterialId }, null, true, (int)DataAccess.EntityType.InventoryItemEntity);
				AddNavigatorMetaData<MaterialPriceEntity, WarehouseEntity>("Warehouse", "MaterialPrices", (a, b) => a._warehouse = b, a => a._warehouse, (a, b) => a.Warehouse = b, DataAccess.RelationClasses.StaticMaterialPriceRelations.WarehouseEntityUsingWarehouseIdStatic, ()=>new MaterialPriceRelations().WarehouseEntityUsingWarehouseId, null, new int[] { (int)MaterialPriceFieldIndex.WarehouseId }, null, true, (int)DataAccess.EntityType.WarehouseEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static MaterialPriceEntity()
		{
		}

		/// <summary> CTor</summary>
		public MaterialPriceEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public MaterialPriceEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this MaterialPriceEntity</param>
		public MaterialPriceEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for MaterialPrice which data should be fetched into this MaterialPrice object</param>
		public MaterialPriceEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for MaterialPrice which data should be fetched into this MaterialPrice object</param>
		/// <param name="validator">The custom validator object for this MaterialPriceEntity</param>
		public MaterialPriceEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected MaterialPriceEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: MaterialId , Price , WarehouseId .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCMaterialIdPriceWarehouseId()
		{
			var filter = new PredicateExpression();
			filter.Add(DataAccess.HelperClasses.MaterialPriceFields.MaterialId == this.Fields.GetCurrentValue((int)MaterialPriceFieldIndex.MaterialId));
			filter.Add(DataAccess.HelperClasses.MaterialPriceFields.Price == this.Fields.GetCurrentValue((int)MaterialPriceFieldIndex.Price));
			filter.Add(DataAccess.HelperClasses.MaterialPriceFields.WarehouseId == this.Fields.GetCurrentValue((int)MaterialPriceFieldIndex.WarehouseId));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'InventoryItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInventoryItem() { return CreateRelationInfoForNavigator("InventoryItem"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Warehouse' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWarehouse() { return CreateRelationInfoForNavigator("Warehouse"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this MaterialPriceEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static MaterialPriceRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InventoryItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInventoryItem { get { return _staticMetaData.GetPrefetchPathElement("InventoryItem", CommonEntityBase.CreateEntityCollection<InventoryItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Warehouse' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWarehouse { get { return _staticMetaData.GetPrefetchPathElement("Warehouse", CommonEntityBase.CreateEntityCollection<WarehouseEntity>()); } }

		/// <summary>The Id property of the Entity MaterialPrice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialPrice"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)MaterialPriceFieldIndex.Id, true); }
			set { SetValue((int)MaterialPriceFieldIndex.Id, value); }
		}

		/// <summary>The MaterialId property of the Entity MaterialPrice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialPrice"."MaterialId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String MaterialId
		{
			get { return (System.String)GetValue((int)MaterialPriceFieldIndex.MaterialId, true); }
			set { SetValue((int)MaterialPriceFieldIndex.MaterialId, value); }
		}

		/// <summary>The Price property of the Entity MaterialPrice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialPrice"."Price".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Double Price
		{
			get { return (System.Double)GetValue((int)MaterialPriceFieldIndex.Price, true); }
			set { SetValue((int)MaterialPriceFieldIndex.Price, value); }
		}

		/// <summary>The Quantity property of the Entity MaterialPrice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialPrice"."Quantity".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Quantity
		{
			get { return (Nullable<System.Double>)GetValue((int)MaterialPriceFieldIndex.Quantity, false); }
			set { SetValue((int)MaterialPriceFieldIndex.Quantity, value); }
		}

		/// <summary>The WarehouseId property of the Entity MaterialPrice<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialPrice"."WarehouseId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String WarehouseId
		{
			get { return (System.String)GetValue((int)MaterialPriceFieldIndex.WarehouseId, true); }
			set { SetValue((int)MaterialPriceFieldIndex.WarehouseId, value); }
		}

		/// <summary>Gets / sets related entity of type 'InventoryItemEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual InventoryItemEntity InventoryItem
		{
			get { return _inventoryItem; }
			set { SetSingleRelatedEntityNavigator(value, "InventoryItem"); }
		}

		/// <summary>Gets / sets related entity of type 'WarehouseEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual WarehouseEntity Warehouse
		{
			get { return _warehouse; }
			set { SetSingleRelatedEntityNavigator(value, "Warehouse"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum MaterialPriceFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>MaterialId. </summary>
		MaterialId,
		///<summary>Price. </summary>
		Price,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>WarehouseId. </summary>
		WarehouseId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: MaterialPrice. </summary>
	public partial class MaterialPriceRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between MaterialPriceEntity and InventoryItemEntity over the m:1 relation they have, using the relation between the fields: MaterialPrice.MaterialId - InventoryItem.MaterialId</summary>
		public virtual IEntityRelation InventoryItemEntityUsingMaterialId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "InventoryItem", false, new[] { InventoryItemFields.MaterialId, MaterialPriceFields.MaterialId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between MaterialPriceEntity and WarehouseEntity over the m:1 relation they have, using the relation between the fields: MaterialPrice.WarehouseId - Warehouse.WarehouseId</summary>
		public virtual IEntityRelation WarehouseEntityUsingWarehouseId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Warehouse", false, new[] { WarehouseFields.WarehouseId, MaterialPriceFields.WarehouseId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticMaterialPriceRelations
	{
		internal static readonly IEntityRelation InventoryItemEntityUsingMaterialIdStatic = new MaterialPriceRelations().InventoryItemEntityUsingMaterialId;
		internal static readonly IEntityRelation WarehouseEntityUsingWarehouseIdStatic = new MaterialPriceRelations().WarehouseEntityUsingWarehouseId;

		/// <summary>CTor</summary>
		static StaticMaterialPriceRelations() { }
	}
}
