//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'MaterialTaxLine'.<br/><br/></summary>
	[Serializable]
	public partial class MaterialTaxLineEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private InventoryVoucherLineEntity _inventoryVoucherLine;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static MaterialTaxLineEntityStaticMetaData _staticMetaData = new MaterialTaxLineEntityStaticMetaData();
		private static MaterialTaxLineRelations _relationsFactory = new MaterialTaxLineRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name InventoryVoucherLine</summary>
			public static readonly string InventoryVoucherLine = "InventoryVoucherLine";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class MaterialTaxLineEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public MaterialTaxLineEntityStaticMetaData()
			{
				SetEntityCoreInfo("MaterialTaxLineEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.MaterialTaxLineEntity, typeof(MaterialTaxLineEntity), typeof(MaterialTaxLineEntityFactory), false);
				AddNavigatorMetaData<MaterialTaxLineEntity, InventoryVoucherLineEntity>("InventoryVoucherLine", "MaterialTaxLine", (a, b) => a._inventoryVoucherLine = b, a => a._inventoryVoucherLine, (a, b) => a.InventoryVoucherLine = b, DataAccess.RelationClasses.StaticMaterialTaxLineRelations.InventoryVoucherLineEntityUsingLineIdStatic, ()=>new MaterialTaxLineRelations().InventoryVoucherLineEntityUsingLineId, null, new int[] { (int)MaterialTaxLineFieldIndex.LineId }, null, false, (int)DataAccess.EntityType.InventoryVoucherLineEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static MaterialTaxLineEntity()
		{
		}

		/// <summary> CTor</summary>
		public MaterialTaxLineEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public MaterialTaxLineEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this MaterialTaxLineEntity</param>
		public MaterialTaxLineEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="lineId">PK value for MaterialTaxLine which data should be fetched into this MaterialTaxLine object</param>
		public MaterialTaxLineEntity(System.Int32 lineId) : this(lineId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="lineId">PK value for MaterialTaxLine which data should be fetched into this MaterialTaxLine object</param>
		/// <param name="validator">The custom validator object for this MaterialTaxLineEntity</param>
		public MaterialTaxLineEntity(System.Int32 lineId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.LineId = lineId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected MaterialTaxLineEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'InventoryVoucherLine' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInventoryVoucherLine() { return CreateRelationInfoForNavigator("InventoryVoucherLine"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this MaterialTaxLineEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static MaterialTaxLineRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InventoryVoucherLine' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInventoryVoucherLine { get { return _staticMetaData.GetPrefetchPathElement("InventoryVoucherLine", CommonEntityBase.CreateEntityCollection<InventoryVoucherLineEntity>()); } }

		/// <summary>The LineId property of the Entity MaterialTaxLine<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialTaxLine"."LineId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int32 LineId
		{
			get { return (System.Int32)GetValue((int)MaterialTaxLineFieldIndex.LineId, true); }
			set { SetValue((int)MaterialTaxLineFieldIndex.LineId, value); }
		}

		/// <summary>The Rate property of the Entity MaterialTaxLine<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialTaxLine"."Rate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Rate
		{
			get { return (Nullable<System.Double>)GetValue((int)MaterialTaxLineFieldIndex.Rate, false); }
			set { SetValue((int)MaterialTaxLineFieldIndex.Rate, value); }
		}

		/// <summary>The SellPrice property of the Entity MaterialTaxLine<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialTaxLine"."SellPrice".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> SellPrice
		{
			get { return (Nullable<System.Double>)GetValue((int)MaterialTaxLineFieldIndex.SellPrice, false); }
			set { SetValue((int)MaterialTaxLineFieldIndex.SellPrice, value); }
		}

		/// <summary>The Taxrateid property of the Entity MaterialTaxLine<br/><br/></summary>
		/// <remarks>Mapped on  table field: "MaterialTaxLine"."Taxrateid".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Taxrateid
		{
			get { return (Nullable<System.Int16>)GetValue((int)MaterialTaxLineFieldIndex.Taxrateid, false); }
			set { SetValue((int)MaterialTaxLineFieldIndex.Taxrateid, value); }
		}

		/// <summary>Gets / sets related entity of type 'InventoryVoucherLineEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned.<br/><br/></summary>
		[Browsable(false)]
		public virtual InventoryVoucherLineEntity InventoryVoucherLine
		{
			get { return _inventoryVoucherLine; }
			set { SetSingleRelatedEntityNavigator(value, "InventoryVoucherLine"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum MaterialTaxLineFieldIndex
	{
		///<summary>LineId. </summary>
		LineId,
		///<summary>Rate. </summary>
		Rate,
		///<summary>SellPrice. </summary>
		SellPrice,
		///<summary>Taxrateid. </summary>
		Taxrateid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: MaterialTaxLine. </summary>
	public partial class MaterialTaxLineRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between MaterialTaxLineEntity and InventoryVoucherLineEntity over the 1:1 relation they have, using the relation between the fields: MaterialTaxLine.LineId - InventoryVoucherLine.Id</summary>
		public virtual IEntityRelation InventoryVoucherLineEntityUsingLineId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToOne, "InventoryVoucherLine", false, new[] { InventoryVoucherLineFields.Id, MaterialTaxLineFields.LineId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticMaterialTaxLineRelations
	{
		internal static readonly IEntityRelation InventoryVoucherLineEntityUsingLineIdStatic = new MaterialTaxLineRelations().InventoryVoucherLineEntityUsingLineId;

		/// <summary>CTor</summary>
		static StaticMaterialTaxLineRelations() { }
	}
}
