//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Partner'.<br/><br/></summary>
	[Serializable]
	public partial class PartnerEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<CustomerExportLineEntity> _customerExportLines;
		private EntityCollection<DebtDetailEntity> _debtDetails;
		private EntityCollection<DebtLedgerEntity> _debtLedgers;
		private EntityCollection<InterestEntity> _interests;
		private EntityCollection<InvestmentDetailEntity> _investmentDetails;
		private EntityCollection<LiabilityDueEntity> _liabilityDues;
		private EntityCollection<SpecialValueEntity> _specialValues;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static PartnerEntityStaticMetaData _staticMetaData = new PartnerEntityStaticMetaData();
		private static PartnerRelations _relationsFactory = new PartnerRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name CustomerExportLines</summary>
			public static readonly string CustomerExportLines = "CustomerExportLines";
			/// <summary>Member name DebtDetails</summary>
			public static readonly string DebtDetails = "DebtDetails";
			/// <summary>Member name DebtLedgers</summary>
			public static readonly string DebtLedgers = "DebtLedgers";
			/// <summary>Member name Interests</summary>
			public static readonly string Interests = "Interests";
			/// <summary>Member name InvestmentDetails</summary>
			public static readonly string InvestmentDetails = "InvestmentDetails";
			/// <summary>Member name LiabilityDues</summary>
			public static readonly string LiabilityDues = "LiabilityDues";
			/// <summary>Member name SpecialValues</summary>
			public static readonly string SpecialValues = "SpecialValues";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PartnerEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PartnerEntityStaticMetaData()
			{
				SetEntityCoreInfo("PartnerEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.PartnerEntity, typeof(PartnerEntity), typeof(PartnerEntityFactory), false);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<CustomerExportLineEntity>>("CustomerExportLines", a => a._customerExportLines, (a, b) => a._customerExportLines = b, a => a.CustomerExportLines, () => new PartnerRelations().CustomerExportLineEntityUsingCustomerId, typeof(CustomerExportLineEntity), (int)DataAccess.EntityType.CustomerExportLineEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<DebtDetailEntity>>("DebtDetails", a => a._debtDetails, (a, b) => a._debtDetails = b, a => a.DebtDetails, () => new PartnerRelations().DebtDetailEntityUsingPartnerId, typeof(DebtDetailEntity), (int)DataAccess.EntityType.DebtDetailEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<DebtLedgerEntity>>("DebtLedgers", a => a._debtLedgers, (a, b) => a._debtLedgers = b, a => a.DebtLedgers, () => new PartnerRelations().DebtLedgerEntityUsingCustomerId, typeof(DebtLedgerEntity), (int)DataAccess.EntityType.DebtLedgerEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<InterestEntity>>("Interests", a => a._interests, (a, b) => a._interests = b, a => a.Interests, () => new PartnerRelations().InterestEntityUsingCustomerId, typeof(InterestEntity), (int)DataAccess.EntityType.InterestEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<InvestmentDetailEntity>>("InvestmentDetails", a => a._investmentDetails, (a, b) => a._investmentDetails = b, a => a.InvestmentDetails, () => new PartnerRelations().InvestmentDetailEntityUsingCustomerId, typeof(InvestmentDetailEntity), (int)DataAccess.EntityType.InvestmentDetailEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<LiabilityDueEntity>>("LiabilityDues", a => a._liabilityDues, (a, b) => a._liabilityDues = b, a => a.LiabilityDues, () => new PartnerRelations().LiabilityDueEntityUsingCustomerId, typeof(LiabilityDueEntity), (int)DataAccess.EntityType.LiabilityDueEntity);
				AddNavigatorMetaData<PartnerEntity, EntityCollection<SpecialValueEntity>>("SpecialValues", a => a._specialValues, (a, b) => a._specialValues = b, a => a.SpecialValues, () => new PartnerRelations().SpecialValueEntityUsingCustomerId, typeof(SpecialValueEntity), (int)DataAccess.EntityType.SpecialValueEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PartnerEntity()
		{
		}

		/// <summary> CTor</summary>
		public PartnerEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PartnerEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PartnerEntity</param>
		public PartnerEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Partner which data should be fetched into this Partner object</param>
		public PartnerEntity(System.String id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Partner which data should be fetched into this Partner object</param>
		/// <param name="validator">The custom validator object for this PartnerEntity</param>
		public PartnerEntity(System.String id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PartnerEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CustomerExportLine' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCustomerExportLines() { return CreateRelationInfoForNavigator("CustomerExportLines"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'DebtDetail' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtDetails() { return CreateRelationInfoForNavigator("DebtDetails"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'DebtLedger' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoDebtLedgers() { return CreateRelationInfoForNavigator("DebtLedgers"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Interest' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInterests() { return CreateRelationInfoForNavigator("Interests"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InvestmentDetail' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvestmentDetails() { return CreateRelationInfoForNavigator("InvestmentDetails"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'LiabilityDue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoLiabilityDues() { return CreateRelationInfoForNavigator("LiabilityDues"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'SpecialValue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSpecialValues() { return CreateRelationInfoForNavigator("SpecialValues"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PartnerEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PartnerRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CustomerExportLine' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCustomerExportLines { get { return _staticMetaData.GetPrefetchPathElement("CustomerExportLines", CommonEntityBase.CreateEntityCollection<CustomerExportLineEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtDetail' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtDetails { get { return _staticMetaData.GetPrefetchPathElement("DebtDetails", CommonEntityBase.CreateEntityCollection<DebtDetailEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DebtLedger' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathDebtLedgers { get { return _staticMetaData.GetPrefetchPathElement("DebtLedgers", CommonEntityBase.CreateEntityCollection<DebtLedgerEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Interest' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInterests { get { return _staticMetaData.GetPrefetchPathElement("Interests", CommonEntityBase.CreateEntityCollection<InterestEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvestmentDetail' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvestmentDetails { get { return _staticMetaData.GetPrefetchPathElement("InvestmentDetails", CommonEntityBase.CreateEntityCollection<InvestmentDetailEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LiabilityDue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathLiabilityDues { get { return _staticMetaData.GetPrefetchPathElement("LiabilityDues", CommonEntityBase.CreateEntityCollection<LiabilityDueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'SpecialValue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSpecialValues { get { return _staticMetaData.GetPrefetchPathElement("SpecialValues", CommonEntityBase.CreateEntityCollection<SpecialValueEntity>()); } }

		/// <summary>The Address property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Address".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Address
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Address, true); }
			set { SetValue((int)PartnerFieldIndex.Address, value); }
		}

		/// <summary>The CustomerName property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."CustomerName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CustomerName
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.CustomerName, true); }
			set { SetValue((int)PartnerFieldIndex.CustomerName, value); }
		}

		/// <summary>The Faxnumber property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Faxnumber".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Faxnumber
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Faxnumber, true); }
			set { SetValue((int)PartnerFieldIndex.Faxnumber, value); }
		}

		/// <summary>The Id property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Id".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Id
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Id, true); }
			set { SetValue((int)PartnerFieldIndex.Id, value); }
		}

		/// <summary>The Isemployee property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Isemployee".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Isemployee
		{
			get { return (System.Boolean)GetValue((int)PartnerFieldIndex.Isemployee, true); }
			set { SetValue((int)PartnerFieldIndex.Isemployee, value); }
		}

		/// <summary>The Note property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Note".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Note
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Note, true); }
			set { SetValue((int)PartnerFieldIndex.Note, value); }
		}

		/// <summary>The Phonenumber property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Phonenumber".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 30.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Phonenumber
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Phonenumber, true); }
			set { SetValue((int)PartnerFieldIndex.Phonenumber, value); }
		}

		/// <summary>The Taxno property of the Entity Partner<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Partner"."Taxno".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Taxno
		{
			get { return (System.String)GetValue((int)PartnerFieldIndex.Taxno, true); }
			set { SetValue((int)PartnerFieldIndex.Taxno, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CustomerExportLineEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CustomerExportLineEntity))]
		public virtual EntityCollection<CustomerExportLineEntity> CustomerExportLines { get { return GetOrCreateEntityCollection<CustomerExportLineEntity, CustomerExportLineEntityFactory>("Partner", true, false, ref _customerExportLines); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'DebtDetailEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(DebtDetailEntity))]
		public virtual EntityCollection<DebtDetailEntity> DebtDetails { get { return GetOrCreateEntityCollection<DebtDetailEntity, DebtDetailEntityFactory>("Partner", true, false, ref _debtDetails); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'DebtLedgerEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(DebtLedgerEntity))]
		public virtual EntityCollection<DebtLedgerEntity> DebtLedgers { get { return GetOrCreateEntityCollection<DebtLedgerEntity, DebtLedgerEntityFactory>("Partner", true, false, ref _debtLedgers); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'InterestEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InterestEntity))]
		public virtual EntityCollection<InterestEntity> Interests { get { return GetOrCreateEntityCollection<InterestEntity, InterestEntityFactory>("Partner", true, false, ref _interests); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'InvestmentDetailEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InvestmentDetailEntity))]
		public virtual EntityCollection<InvestmentDetailEntity> InvestmentDetails { get { return GetOrCreateEntityCollection<InvestmentDetailEntity, InvestmentDetailEntityFactory>("Partner", true, false, ref _investmentDetails); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'LiabilityDueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(LiabilityDueEntity))]
		public virtual EntityCollection<LiabilityDueEntity> LiabilityDues { get { return GetOrCreateEntityCollection<LiabilityDueEntity, LiabilityDueEntityFactory>("Partner", true, false, ref _liabilityDues); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'SpecialValueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(SpecialValueEntity))]
		public virtual EntityCollection<SpecialValueEntity> SpecialValues { get { return GetOrCreateEntityCollection<SpecialValueEntity, SpecialValueEntityFactory>("Partner", true, false, ref _specialValues); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum PartnerFieldIndex
	{
		///<summary>Address. </summary>
		Address,
		///<summary>CustomerName. </summary>
		CustomerName,
		///<summary>Faxnumber. </summary>
		Faxnumber,
		///<summary>Id. </summary>
		Id,
		///<summary>Isemployee. </summary>
		Isemployee,
		///<summary>Note. </summary>
		Note,
		///<summary>Phonenumber. </summary>
		Phonenumber,
		///<summary>Taxno. </summary>
		Taxno,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Partner. </summary>
	public partial class PartnerRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and CustomerExportLineEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - CustomerExportLine.CustomerId</summary>
		public virtual IEntityRelation CustomerExportLineEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CustomerExportLines", true, new[] { PartnerFields.Id, CustomerExportLineFields.CustomerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and DebtDetailEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - DebtDetail.PartnerId</summary>
		public virtual IEntityRelation DebtDetailEntityUsingPartnerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DebtDetails", true, new[] { PartnerFields.Id, DebtDetailFields.PartnerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and DebtLedgerEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - DebtLedger.CustomerId</summary>
		public virtual IEntityRelation DebtLedgerEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DebtLedgers", true, new[] { PartnerFields.Id, DebtLedgerFields.CustomerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and InterestEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - Interest.CustomerId</summary>
		public virtual IEntityRelation InterestEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Interests", true, new[] { PartnerFields.Id, InterestFields.CustomerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and InvestmentDetailEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - InvestmentDetail.CustomerId</summary>
		public virtual IEntityRelation InvestmentDetailEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "InvestmentDetails", true, new[] { PartnerFields.Id, InvestmentDetailFields.CustomerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and LiabilityDueEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - LiabilityDue.CustomerId</summary>
		public virtual IEntityRelation LiabilityDueEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "LiabilityDues", true, new[] { PartnerFields.Id, LiabilityDueFields.CustomerId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PartnerEntity and SpecialValueEntity over the 1:n relation they have, using the relation between the fields: Partner.Id - SpecialValue.CustomerId</summary>
		public virtual IEntityRelation SpecialValueEntityUsingCustomerId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "SpecialValues", true, new[] { PartnerFields.Id, SpecialValueFields.CustomerId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPartnerRelations
	{
		internal static readonly IEntityRelation CustomerExportLineEntityUsingCustomerIdStatic = new PartnerRelations().CustomerExportLineEntityUsingCustomerId;
		internal static readonly IEntityRelation DebtDetailEntityUsingPartnerIdStatic = new PartnerRelations().DebtDetailEntityUsingPartnerId;
		internal static readonly IEntityRelation DebtLedgerEntityUsingCustomerIdStatic = new PartnerRelations().DebtLedgerEntityUsingCustomerId;
		internal static readonly IEntityRelation InterestEntityUsingCustomerIdStatic = new PartnerRelations().InterestEntityUsingCustomerId;
		internal static readonly IEntityRelation InvestmentDetailEntityUsingCustomerIdStatic = new PartnerRelations().InvestmentDetailEntityUsingCustomerId;
		internal static readonly IEntityRelation LiabilityDueEntityUsingCustomerIdStatic = new PartnerRelations().LiabilityDueEntityUsingCustomerId;
		internal static readonly IEntityRelation SpecialValueEntityUsingCustomerIdStatic = new PartnerRelations().SpecialValueEntityUsingCustomerId;

		/// <summary>CTor</summary>
		static StaticPartnerRelations() { }
	}
}
