//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ReportFormulaAccount'.<br/><br/></summary>
	[Serializable]
	public partial class ReportFormulaAccountEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ReportFormulaEntity _reportFormula;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ReportFormulaAccountEntityStaticMetaData _staticMetaData = new ReportFormulaAccountEntityStaticMetaData();
		private static ReportFormulaAccountRelations _relationsFactory = new ReportFormulaAccountRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ReportFormula</summary>
			public static readonly string ReportFormula = "ReportFormula";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReportFormulaAccountEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReportFormulaAccountEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReportFormulaAccountEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.ReportFormulaAccountEntity, typeof(ReportFormulaAccountEntity), typeof(ReportFormulaAccountEntityFactory), false);
				AddNavigatorMetaData<ReportFormulaAccountEntity, ReportFormulaEntity>("ReportFormula", "ReportFormulaAccounts", (a, b) => a._reportFormula = b, a => a._reportFormula, (a, b) => a.ReportFormula = b, DataAccess.RelationClasses.StaticReportFormulaAccountRelations.ReportFormulaEntityUsingItemsIdStatic, ()=>new ReportFormulaAccountRelations().ReportFormulaEntityUsingItemsId, null, new int[] { (int)ReportFormulaAccountFieldIndex.ItemsId }, null, true, (int)DataAccess.EntityType.ReportFormulaEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReportFormulaAccountEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReportFormulaAccountEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReportFormulaAccountEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReportFormulaAccountEntity</param>
		public ReportFormulaAccountEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ReportFormulaAccount which data should be fetched into this ReportFormulaAccount object</param>
		public ReportFormulaAccountEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for ReportFormulaAccount which data should be fetched into this ReportFormulaAccount object</param>
		/// <param name="validator">The custom validator object for this ReportFormulaAccountEntity</param>
		public ReportFormulaAccountEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReportFormulaAccountEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ReportFormula' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoReportFormula() { return CreateRelationInfoForNavigator("ReportFormula"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReportFormulaAccountEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReportFormulaAccountRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ReportFormula' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathReportFormula { get { return _staticMetaData.GetPrefetchPathElement("ReportFormula", CommonEntityBase.CreateEntityCollection<ReportFormulaEntity>()); } }

		/// <summary>The AccountId property of the Entity ReportFormulaAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ReportFormulaAccount"."AccountId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AccountId
		{
			get { return (System.String)GetValue((int)ReportFormulaAccountFieldIndex.AccountId, true); }
			set { SetValue((int)ReportFormulaAccountFieldIndex.AccountId, value); }
		}

		/// <summary>The Id property of the Entity ReportFormulaAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ReportFormulaAccount"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ReportFormulaAccountFieldIndex.Id, true); }
			set { SetValue((int)ReportFormulaAccountFieldIndex.Id, value); }
		}

		/// <summary>The ItemsId property of the Entity ReportFormulaAccount<br/><br/></summary>
		/// <remarks>Mapped on  table field: "ReportFormulaAccount"."ItemsId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> ItemsId
		{
			get { return (Nullable<System.Int32>)GetValue((int)ReportFormulaAccountFieldIndex.ItemsId, false); }
			set { SetValue((int)ReportFormulaAccountFieldIndex.ItemsId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ReportFormulaEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ReportFormulaEntity ReportFormula
		{
			get { return _reportFormula; }
			set { SetSingleRelatedEntityNavigator(value, "ReportFormula"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum ReportFormulaAccountFieldIndex
	{
		///<summary>AccountId. </summary>
		AccountId,
		///<summary>Id. </summary>
		Id,
		///<summary>ItemsId. </summary>
		ItemsId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ReportFormulaAccount. </summary>
	public partial class ReportFormulaAccountRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReportFormulaAccountEntity and ReportFormulaEntity over the m:1 relation they have, using the relation between the fields: ReportFormulaAccount.ItemsId - ReportFormula.Id</summary>
		public virtual IEntityRelation ReportFormulaEntityUsingItemsId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ReportFormula", false, new[] { ReportFormulaFields.Id, ReportFormulaAccountFields.ItemsId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReportFormulaAccountRelations
	{
		internal static readonly IEntityRelation ReportFormulaEntityUsingItemsIdStatic = new ReportFormulaAccountRelations().ReportFormulaEntityUsingItemsId;

		/// <summary>CTor</summary>
		static StaticReportFormulaAccountRelations() { }
	}
}
