//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'SecurityPolicy'.<br/><br/></summary>
	[Serializable]
	public partial class SecurityPolicyEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SecurityPolicyEntityStaticMetaData _staticMetaData = new SecurityPolicyEntityStaticMetaData();
		private static SecurityPolicyRelations _relationsFactory = new SecurityPolicyRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SecurityPolicyEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SecurityPolicyEntityStaticMetaData()
			{
				SetEntityCoreInfo("SecurityPolicyEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.SecurityPolicyEntity, typeof(SecurityPolicyEntity), typeof(SecurityPolicyEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SecurityPolicyEntity()
		{
		}

		/// <summary> CTor</summary>
		public SecurityPolicyEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SecurityPolicyEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SecurityPolicyEntity</param>
		public SecurityPolicyEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SecurityPolicy which data should be fetched into this SecurityPolicy object</param>
		public SecurityPolicyEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SecurityPolicy which data should be fetched into this SecurityPolicy object</param>
		/// <param name="validator">The custom validator object for this SecurityPolicyEntity</param>
		public SecurityPolicyEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SecurityPolicyEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SecurityPolicyEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SecurityPolicyRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity SecurityPolicy<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SecurityPolicy"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SecurityPolicyFieldIndex.Id, true); }
			set { SetValue((int)SecurityPolicyFieldIndex.Id, value); }
		}

		/// <summary>The SecurityLevel property of the Entity SecurityPolicy<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SecurityPolicy"."SecurityLevel".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SecurityLevel
		{
			get { return (System.String)GetValue((int)SecurityPolicyFieldIndex.SecurityLevel, true); }
			set { SetValue((int)SecurityPolicyFieldIndex.SecurityLevel, value); }
		}

		/// <summary>The UserName property of the Entity SecurityPolicy<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SecurityPolicy"."UserName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String UserName
		{
			get { return (System.String)GetValue((int)SecurityPolicyFieldIndex.UserName, true); }
			set { SetValue((int)SecurityPolicyFieldIndex.UserName, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum SecurityPolicyFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>SecurityLevel. </summary>
		SecurityLevel,
		///<summary>UserName. </summary>
		UserName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SecurityPolicy. </summary>
	public partial class SecurityPolicyRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSecurityPolicyRelations
	{

		/// <summary>CTor</summary>
		static StaticSecurityPolicyRelations() { }
	}
}
