//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Stock'.<br/><br/></summary>
	[Serializable]
	public partial class StockEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<InvestmentDetailEntity> _investmentDetails;
		private StockTypeEntity _stockType;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static StockEntityStaticMetaData _staticMetaData = new StockEntityStaticMetaData();
		private static StockRelations _relationsFactory = new StockRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name StockType</summary>
			public static readonly string StockType = "StockType";
			/// <summary>Member name InvestmentDetails</summary>
			public static readonly string InvestmentDetails = "InvestmentDetails";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class StockEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public StockEntityStaticMetaData()
			{
				SetEntityCoreInfo("StockEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.StockEntity, typeof(StockEntity), typeof(StockEntityFactory), false);
				AddNavigatorMetaData<StockEntity, EntityCollection<InvestmentDetailEntity>>("InvestmentDetails", a => a._investmentDetails, (a, b) => a._investmentDetails = b, a => a.InvestmentDetails, () => new StockRelations().InvestmentDetailEntityUsingStockid, typeof(InvestmentDetailEntity), (int)DataAccess.EntityType.InvestmentDetailEntity);
				AddNavigatorMetaData<StockEntity, StockTypeEntity>("StockType", "Stocks", (a, b) => a._stockType = b, a => a._stockType, (a, b) => a.StockType = b, DataAccess.RelationClasses.StaticStockRelations.StockTypeEntityUsingStocktypeidStatic, ()=>new StockRelations().StockTypeEntityUsingStocktypeid, null, new int[] { (int)StockFieldIndex.Stocktypeid }, null, true, (int)DataAccess.EntityType.StockTypeEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static StockEntity()
		{
		}

		/// <summary> CTor</summary>
		public StockEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public StockEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this StockEntity</param>
		public StockEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="stockid">PK value for Stock which data should be fetched into this Stock object</param>
		public StockEntity(System.String stockid) : this(stockid, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="stockid">PK value for Stock which data should be fetched into this Stock object</param>
		/// <param name="validator">The custom validator object for this StockEntity</param>
		public StockEntity(System.String stockid, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Stockid = stockid;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected StockEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'InvestmentDetail' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoInvestmentDetails() { return CreateRelationInfoForNavigator("InvestmentDetails"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'StockType' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoStockType() { return CreateRelationInfoForNavigator("StockType"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this StockEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static StockRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InvestmentDetail' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathInvestmentDetails { get { return _staticMetaData.GetPrefetchPathElement("InvestmentDetails", CommonEntityBase.CreateEntityCollection<InvestmentDetailEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StockType' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathStockType { get { return _staticMetaData.GetPrefetchPathElement("StockType", CommonEntityBase.CreateEntityCollection<StockTypeEntity>()); } }

		/// <summary>The Description property of the Entity Stock<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Stock"."Description".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)StockFieldIndex.Description, true); }
			set { SetValue((int)StockFieldIndex.Description, value); }
		}

		/// <summary>The Stockid property of the Entity Stock<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Stock"."Stockid".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Stockid
		{
			get { return (System.String)GetValue((int)StockFieldIndex.Stockid, true); }
			set { SetValue((int)StockFieldIndex.Stockid, value); }
		}

		/// <summary>The Stocktypeid property of the Entity Stock<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Stock"."Stocktypeid".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int16> Stocktypeid
		{
			get { return (Nullable<System.Int16>)GetValue((int)StockFieldIndex.Stocktypeid, false); }
			set { SetValue((int)StockFieldIndex.Stocktypeid, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'InvestmentDetailEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(InvestmentDetailEntity))]
		public virtual EntityCollection<InvestmentDetailEntity> InvestmentDetails { get { return GetOrCreateEntityCollection<InvestmentDetailEntity, InvestmentDetailEntityFactory>("Stock", true, false, ref _investmentDetails); } }

		/// <summary>Gets / sets related entity of type 'StockTypeEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual StockTypeEntity StockType
		{
			get { return _stockType; }
			set { SetSingleRelatedEntityNavigator(value, "StockType"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum StockFieldIndex
	{
		///<summary>Description. </summary>
		Description,
		///<summary>Stockid. </summary>
		Stockid,
		///<summary>Stocktypeid. </summary>
		Stocktypeid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Stock. </summary>
	public partial class StockRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between StockEntity and InvestmentDetailEntity over the 1:n relation they have, using the relation between the fields: Stock.Stockid - InvestmentDetail.Stockid</summary>
		public virtual IEntityRelation InvestmentDetailEntityUsingStockid
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "InvestmentDetails", true, new[] { StockFields.Stockid, InvestmentDetailFields.Stockid }); }
		}

		/// <summary>Returns a new IEntityRelation object, between StockEntity and StockTypeEntity over the m:1 relation they have, using the relation between the fields: Stock.Stocktypeid - StockType.Stocktypeid</summary>
		public virtual IEntityRelation StockTypeEntityUsingStocktypeid
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "StockType", false, new[] { StockTypeFields.Stocktypeid, StockFields.Stocktypeid }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticStockRelations
	{
		internal static readonly IEntityRelation InvestmentDetailEntityUsingStockidStatic = new StockRelations().InvestmentDetailEntityUsingStockid;
		internal static readonly IEntityRelation StockTypeEntityUsingStocktypeidStatic = new StockRelations().StockTypeEntityUsingStocktypeid;

		/// <summary>CTor</summary>
		static StaticStockRelations() { }
	}
}
