//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'TaxObligationItem'.<br/><br/></summary>
	[Serializable]
	public partial class TaxObligationItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AccountTaxObligationEntity> _accountTaxObligations;
		private TaxObligationEntity _taxObligation;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static TaxObligationItemEntityStaticMetaData _staticMetaData = new TaxObligationItemEntityStaticMetaData();
		private static TaxObligationItemRelations _relationsFactory = new TaxObligationItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name TaxObligation</summary>
			public static readonly string TaxObligation = "TaxObligation";
			/// <summary>Member name AccountTaxObligations</summary>
			public static readonly string AccountTaxObligations = "AccountTaxObligations";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class TaxObligationItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public TaxObligationItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("TaxObligationItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.TaxObligationItemEntity, typeof(TaxObligationItemEntity), typeof(TaxObligationItemEntityFactory), false);
				AddNavigatorMetaData<TaxObligationItemEntity, EntityCollection<AccountTaxObligationEntity>>("AccountTaxObligations", a => a._accountTaxObligations, (a, b) => a._accountTaxObligations = b, a => a.AccountTaxObligations, () => new TaxObligationItemRelations().AccountTaxObligationEntityUsingTaxObligationItemId, typeof(AccountTaxObligationEntity), (int)DataAccess.EntityType.AccountTaxObligationEntity);
				AddNavigatorMetaData<TaxObligationItemEntity, TaxObligationEntity>("TaxObligation", "TaxObligationItems", (a, b) => a._taxObligation = b, a => a._taxObligation, (a, b) => a.TaxObligation = b, DataAccess.RelationClasses.StaticTaxObligationItemRelations.TaxObligationEntityUsingTaxObligationIdStatic, ()=>new TaxObligationItemRelations().TaxObligationEntityUsingTaxObligationId, null, new int[] { (int)TaxObligationItemFieldIndex.TaxObligationId }, null, true, (int)DataAccess.EntityType.TaxObligationEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static TaxObligationItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public TaxObligationItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public TaxObligationItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this TaxObligationItemEntity</param>
		public TaxObligationItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for TaxObligationItem which data should be fetched into this TaxObligationItem object</param>
		public TaxObligationItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for TaxObligationItem which data should be fetched into this TaxObligationItem object</param>
		/// <param name="validator">The custom validator object for this TaxObligationItemEntity</param>
		public TaxObligationItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected TaxObligationItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AccountTaxObligation' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccountTaxObligations() { return CreateRelationInfoForNavigator("AccountTaxObligations"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'TaxObligation' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTaxObligation() { return CreateRelationInfoForNavigator("TaxObligation"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this TaxObligationItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static TaxObligationItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AccountTaxObligation' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccountTaxObligations { get { return _staticMetaData.GetPrefetchPathElement("AccountTaxObligations", CommonEntityBase.CreateEntityCollection<AccountTaxObligationEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'TaxObligation' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTaxObligation { get { return _staticMetaData.GetPrefetchPathElement("TaxObligation", CommonEntityBase.CreateEntityCollection<TaxObligationEntity>()); } }

		/// <summary>The Code property of the Entity TaxObligationItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxObligationItem"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)TaxObligationItemFieldIndex.Code, true); }
			set { SetValue((int)TaxObligationItemFieldIndex.Code, value); }
		}

		/// <summary>The Id property of the Entity TaxObligationItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxObligationItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)TaxObligationItemFieldIndex.Id, true); }
			set { SetValue((int)TaxObligationItemFieldIndex.Id, value); }
		}

		/// <summary>The ItemName property of the Entity TaxObligationItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxObligationItem"."ItemName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemName
		{
			get { return (System.String)GetValue((int)TaxObligationItemFieldIndex.ItemName, true); }
			set { SetValue((int)TaxObligationItemFieldIndex.ItemName, value); }
		}

		/// <summary>The TaxObligationId property of the Entity TaxObligationItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxObligationItem"."TaxObligationId".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> TaxObligationId
		{
			get { return (Nullable<System.Int32>)GetValue((int)TaxObligationItemFieldIndex.TaxObligationId, false); }
			set { SetValue((int)TaxObligationItemFieldIndex.TaxObligationId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AccountTaxObligationEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AccountTaxObligationEntity))]
		public virtual EntityCollection<AccountTaxObligationEntity> AccountTaxObligations { get { return GetOrCreateEntityCollection<AccountTaxObligationEntity, AccountTaxObligationEntityFactory>("TaxObligationItem", true, false, ref _accountTaxObligations); } }

		/// <summary>Gets / sets related entity of type 'TaxObligationEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual TaxObligationEntity TaxObligation
		{
			get { return _taxObligation; }
			set { SetSingleRelatedEntityNavigator(value, "TaxObligation"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum TaxObligationItemFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>Id. </summary>
		Id,
		///<summary>ItemName. </summary>
		ItemName,
		///<summary>TaxObligationId. </summary>
		TaxObligationId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: TaxObligationItem. </summary>
	public partial class TaxObligationItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between TaxObligationItemEntity and AccountTaxObligationEntity over the 1:n relation they have, using the relation between the fields: TaxObligationItem.Id - AccountTaxObligation.TaxObligationItemId</summary>
		public virtual IEntityRelation AccountTaxObligationEntityUsingTaxObligationItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AccountTaxObligations", true, new[] { TaxObligationItemFields.Id, AccountTaxObligationFields.TaxObligationItemId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between TaxObligationItemEntity and TaxObligationEntity over the m:1 relation they have, using the relation between the fields: TaxObligationItem.TaxObligationId - TaxObligation.Id</summary>
		public virtual IEntityRelation TaxObligationEntityUsingTaxObligationId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "TaxObligation", false, new[] { TaxObligationFields.Id, TaxObligationItemFields.TaxObligationId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticTaxObligationItemRelations
	{
		internal static readonly IEntityRelation AccountTaxObligationEntityUsingTaxObligationItemIdStatic = new TaxObligationItemRelations().AccountTaxObligationEntityUsingTaxObligationItemId;
		internal static readonly IEntityRelation TaxObligationEntityUsingTaxObligationIdStatic = new TaxObligationItemRelations().TaxObligationEntityUsingTaxObligationId;

		/// <summary>CTor</summary>
		static StaticTaxObligationItemRelations() { }
	}
}
