//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'TaxRate'.<br/><br/></summary>
	[Serializable]
	public partial class TaxRateEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static TaxRateEntityStaticMetaData _staticMetaData = new TaxRateEntityStaticMetaData();
		private static TaxRateRelations _relationsFactory = new TaxRateRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class TaxRateEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public TaxRateEntityStaticMetaData()
			{
				SetEntityCoreInfo("TaxRateEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.TaxRateEntity, typeof(TaxRateEntity), typeof(TaxRateEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static TaxRateEntity()
		{
		}

		/// <summary> CTor</summary>
		public TaxRateEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public TaxRateEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this TaxRateEntity</param>
		public TaxRateEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="taxrateid">PK value for TaxRate which data should be fetched into this TaxRate object</param>
		public TaxRateEntity(System.Int32 taxrateid) : this(taxrateid, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="taxrateid">PK value for TaxRate which data should be fetched into this TaxRate object</param>
		/// <param name="validator">The custom validator object for this TaxRateEntity</param>
		public TaxRateEntity(System.Int32 taxrateid, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Taxrateid = taxrateid;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected TaxRateEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this TaxRateEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static TaxRateRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Rate property of the Entity TaxRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxRate"."Rate".<br/>Table field type characteristics (type, precision, scale, length): Float, 15, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Double> Rate
		{
			get { return (Nullable<System.Double>)GetValue((int)TaxRateFieldIndex.Rate, false); }
			set { SetValue((int)TaxRateFieldIndex.Rate, value); }
		}

		/// <summary>The Taxratedes property of the Entity TaxRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxRate"."Taxratedes".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Taxratedes
		{
			get { return (System.String)GetValue((int)TaxRateFieldIndex.Taxratedes, true); }
			set { SetValue((int)TaxRateFieldIndex.Taxratedes, value); }
		}

		/// <summary>The Taxrateid property of the Entity TaxRate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "TaxRate"."Taxrateid".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Taxrateid
		{
			get { return (System.Int32)GetValue((int)TaxRateFieldIndex.Taxrateid, true); }
			set { SetValue((int)TaxRateFieldIndex.Taxrateid, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum TaxRateFieldIndex
	{
		///<summary>Rate. </summary>
		Rate,
		///<summary>Taxratedes. </summary>
		Taxratedes,
		///<summary>Taxrateid. </summary>
		Taxrateid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: TaxRate. </summary>
	public partial class TaxRateRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticTaxRateRelations
	{

		/// <summary>CTor</summary>
		static StaticTaxRateRelations() { }
	}
}
