//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Vat3TaxItem'.<br/><br/></summary>
	[Serializable]
	public partial class Vat3TaxItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AccountVat3ItemEntity> _accountVat3Items;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static Vat3TaxItemEntityStaticMetaData _staticMetaData = new Vat3TaxItemEntityStaticMetaData();
		private static Vat3TaxItemRelations _relationsFactory = new Vat3TaxItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AccountVat3Items</summary>
			public static readonly string AccountVat3Items = "AccountVat3Items";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class Vat3TaxItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public Vat3TaxItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("Vat3TaxItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.Vat3TaxItemEntity, typeof(Vat3TaxItemEntity), typeof(Vat3TaxItemEntityFactory), false);
				AddNavigatorMetaData<Vat3TaxItemEntity, EntityCollection<AccountVat3ItemEntity>>("AccountVat3Items", a => a._accountVat3Items, (a, b) => a._accountVat3Items = b, a => a.AccountVat3Items, () => new Vat3TaxItemRelations().AccountVat3ItemEntityUsingVat3TaxItemId, typeof(AccountVat3ItemEntity), (int)DataAccess.EntityType.AccountVat3ItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static Vat3TaxItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public Vat3TaxItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public Vat3TaxItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this Vat3TaxItemEntity</param>
		public Vat3TaxItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Vat3TaxItem which data should be fetched into this Vat3TaxItem object</param>
		public Vat3TaxItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Vat3TaxItem which data should be fetched into this Vat3TaxItem object</param>
		/// <param name="validator">The custom validator object for this Vat3TaxItemEntity</param>
		public Vat3TaxItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected Vat3TaxItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AccountVat3Item' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccountVat3Items() { return CreateRelationInfoForNavigator("AccountVat3Items"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this Vat3TaxItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static Vat3TaxItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AccountVat3Item' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccountVat3Items { get { return _staticMetaData.GetPrefetchPathElement("AccountVat3Items", CommonEntityBase.CreateEntityCollection<AccountVat3ItemEntity>()); } }

		/// <summary>The Code property of the Entity Vat3TaxItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Vat3TaxItem"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)Vat3TaxItemFieldIndex.Code, true); }
			set { SetValue((int)Vat3TaxItemFieldIndex.Code, value); }
		}

		/// <summary>The Id property of the Entity Vat3TaxItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Vat3TaxItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)Vat3TaxItemFieldIndex.Id, true); }
			set { SetValue((int)Vat3TaxItemFieldIndex.Id, value); }
		}

		/// <summary>The IsBold property of the Entity Vat3TaxItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Vat3TaxItem"."IsBold".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsBold
		{
			get { return (System.Boolean)GetValue((int)Vat3TaxItemFieldIndex.IsBold, true); }
			set { SetValue((int)Vat3TaxItemFieldIndex.IsBold, value); }
		}

		/// <summary>The IsItalic property of the Entity Vat3TaxItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Vat3TaxItem"."IsItalic".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsItalic
		{
			get { return (System.Boolean)GetValue((int)Vat3TaxItemFieldIndex.IsItalic, true); }
			set { SetValue((int)Vat3TaxItemFieldIndex.IsItalic, value); }
		}

		/// <summary>The ItemName property of the Entity Vat3TaxItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Vat3TaxItem"."ItemName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemName
		{
			get { return (System.String)GetValue((int)Vat3TaxItemFieldIndex.ItemName, true); }
			set { SetValue((int)Vat3TaxItemFieldIndex.ItemName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AccountVat3ItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AccountVat3ItemEntity))]
		public virtual EntityCollection<AccountVat3ItemEntity> AccountVat3Items { get { return GetOrCreateEntityCollection<AccountVat3ItemEntity, AccountVat3ItemEntityFactory>("Vat3TaxItem", true, false, ref _accountVat3Items); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum Vat3TaxItemFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>Id. </summary>
		Id,
		///<summary>IsBold. </summary>
		IsBold,
		///<summary>IsItalic. </summary>
		IsItalic,
		///<summary>ItemName. </summary>
		ItemName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Vat3TaxItem. </summary>
	public partial class Vat3TaxItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between Vat3TaxItemEntity and AccountVat3ItemEntity over the 1:n relation they have, using the relation between the fields: Vat3TaxItem.Id - AccountVat3Item.Vat3TaxItemId</summary>
		public virtual IEntityRelation AccountVat3ItemEntityUsingVat3TaxItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AccountVat3Items", true, new[] { Vat3TaxItemFields.Id, AccountVat3ItemFields.Vat3TaxItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVat3TaxItemRelations
	{
		internal static readonly IEntityRelation AccountVat3ItemEntityUsingVat3TaxItemIdStatic = new Vat3TaxItemRelations().AccountVat3ItemEntityUsingVat3TaxItemId;

		/// <summary>CTor</summary>
		static StaticVat3TaxItemRelations() { }
	}
}
