//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using DataAccess.HelperClasses;
using DataAccess.FactoryClasses;
using DataAccess.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace DataAccess.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'VatDeclareItem'.<br/><br/></summary>
	[Serializable]
	public partial class VatDeclareItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<AccountVatDeclareItemEntity> _accountVatDeclareItems;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static VatDeclareItemEntityStaticMetaData _staticMetaData = new VatDeclareItemEntityStaticMetaData();
		private static VatDeclareItemRelations _relationsFactory = new VatDeclareItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name AccountVatDeclareItems</summary>
			public static readonly string AccountVatDeclareItems = "AccountVatDeclareItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class VatDeclareItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public VatDeclareItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("VatDeclareItemEntity", InheritanceHierarchyType.None, false, (int)DataAccess.EntityType.VatDeclareItemEntity, typeof(VatDeclareItemEntity), typeof(VatDeclareItemEntityFactory), false);
				AddNavigatorMetaData<VatDeclareItemEntity, EntityCollection<AccountVatDeclareItemEntity>>("AccountVatDeclareItems", a => a._accountVatDeclareItems, (a, b) => a._accountVatDeclareItems = b, a => a.AccountVatDeclareItems, () => new VatDeclareItemRelations().AccountVatDeclareItemEntityUsingVatDeclareItemId, typeof(AccountVatDeclareItemEntity), (int)DataAccess.EntityType.AccountVatDeclareItemEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static VatDeclareItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public VatDeclareItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public VatDeclareItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this VatDeclareItemEntity</param>
		public VatDeclareItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for VatDeclareItem which data should be fetched into this VatDeclareItem object</param>
		public VatDeclareItemEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for VatDeclareItem which data should be fetched into this VatDeclareItem object</param>
		/// <param name="validator">The custom validator object for this VatDeclareItemEntity</param>
		public VatDeclareItemEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected VatDeclareItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AccountVatDeclareItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoAccountVatDeclareItems() { return CreateRelationInfoForNavigator("AccountVatDeclareItems"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this VatDeclareItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static VatDeclareItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AccountVatDeclareItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathAccountVatDeclareItems { get { return _staticMetaData.GetPrefetchPathElement("AccountVatDeclareItems", CommonEntityBase.CreateEntityCollection<AccountVatDeclareItemEntity>()); } }

		/// <summary>The Code property of the Entity VatDeclareItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VatDeclareItem"."Code".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)VatDeclareItemFieldIndex.Code, true); }
			set { SetValue((int)VatDeclareItemFieldIndex.Code, value); }
		}

		/// <summary>The Id property of the Entity VatDeclareItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VatDeclareItem"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)VatDeclareItemFieldIndex.Id, true); }
			set { SetValue((int)VatDeclareItemFieldIndex.Id, value); }
		}

		/// <summary>The IsBold property of the Entity VatDeclareItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VatDeclareItem"."IsBold".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsBold
		{
			get { return (System.Boolean)GetValue((int)VatDeclareItemFieldIndex.IsBold, true); }
			set { SetValue((int)VatDeclareItemFieldIndex.IsBold, value); }
		}

		/// <summary>The IsItalic property of the Entity VatDeclareItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VatDeclareItem"."IsItalic".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsItalic
		{
			get { return (System.Boolean)GetValue((int)VatDeclareItemFieldIndex.IsItalic, true); }
			set { SetValue((int)VatDeclareItemFieldIndex.IsItalic, value); }
		}

		/// <summary>The ItemName property of the Entity VatDeclareItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "VatDeclareItem"."ItemName".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ItemName
		{
			get { return (System.String)GetValue((int)VatDeclareItemFieldIndex.ItemName, true); }
			set { SetValue((int)VatDeclareItemFieldIndex.ItemName, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'AccountVatDeclareItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(AccountVatDeclareItemEntity))]
		public virtual EntityCollection<AccountVatDeclareItemEntity> AccountVatDeclareItems { get { return GetOrCreateEntityCollection<AccountVatDeclareItemEntity, AccountVatDeclareItemEntityFactory>("VatDeclareItem", true, false, ref _accountVatDeclareItems); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace DataAccess
{
	public enum VatDeclareItemFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>Id. </summary>
		Id,
		///<summary>IsBold. </summary>
		IsBold,
		///<summary>IsItalic. </summary>
		IsItalic,
		///<summary>ItemName. </summary>
		ItemName,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace DataAccess.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: VatDeclareItem. </summary>
	public partial class VatDeclareItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between VatDeclareItemEntity and AccountVatDeclareItemEntity over the 1:n relation they have, using the relation between the fields: VatDeclareItem.Id - AccountVatDeclareItem.VatDeclareItemId</summary>
		public virtual IEntityRelation AccountVatDeclareItemEntityUsingVatDeclareItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AccountVatDeclareItems", true, new[] { VatDeclareItemFields.Id, AccountVatDeclareItemFields.VatDeclareItemId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticVatDeclareItemRelations
	{
		internal static readonly IEntityRelation AccountVatDeclareItemEntityUsingVatDeclareItemIdStatic = new VatDeclareItemRelations().AccountVatDeclareItemEntityUsingVatDeclareItemId;

		/// <summary>CTor</summary>
		static StaticVatDeclareItemRelations() { }
	}
}
